SKINS = GLOBAL.STRINGS.SKIN_NAMES
SKINSDESC = GLOBAL.STRINGS.SKIN_DESCRIPTIONS
NAMES = GLOBAL.STRINGS.NAMES
UI = GLOBAL.STRINGS.UI


--Re-names to existing items
NAMES.AMULET = "Lesser Life Amulet"
NAMES.BEESWAX = "Wax"



-------------------------------------------------- Strings

NAMES.CREEPINGFEAR = "Creeping Fear"
NAMES.DREADEYE     = "Dread Eye"

NAMES.UNCOMPROMISING_RAT = "Rat"          -- Maybe change the name with a pun with Robber or Raider, any idea ?
NAMES.UNCOMPROMISING_CAVERAT = "Cave Rat" -- The aggressive cousin
NAMES.UNCOMPROMISING_PACKRAT = "Pack Rat" -- The hoarding cousin
NAMES.UNCOMPROMISING_RATHERD = "Rat Burrow"
NAMES.UNCOMPROMISING_RATBURROW = "Rat Burrow"
NAMES.UNCOMPROMISING_WINKYBURROW = "Winky's Burrow"
NAMES.UNCOMPROMISING_WINKYBURROW_MASTER = "Winky's Burrow"
NAMES.UNCOMPROMISING_WINKYHOMEBURROW = "Winky's Home Burrow"
NAMES.PIED_RAT = "Pied Piper"
NAMES.PIED_PIPER_FLUTE = "Pied Piper's Pipe"
NAMES.GASMASK = "Goose Mask"
NAMES.WATER = "Rain"
NAMES.RAIN = "Rain"
NAMES.SPORECLOUD_TOAD = "Spore Cloud"
NAMES.MOCK_DRAGONFLY = "Dragonfly"
NAMES.UM_SAND = "Sand"
NAMES.UM_SANDHILL = "Sandy Pile"
NAMES.SNOWPILE = "Snow Pile"
NAMES.SNOWGOGGLES = "Cats-Eye Goggles"
NAMES.UM_SPIDERQUEENCORPSE = "Spider Queen Corpse"
NAMES.RATPOISON = "Poison Jam"
NAMES.RATPOISONBOTTLE = "Poison Jam"
NAMES.LEECHSWARM = "Leech Swarm"
NAMES.LAITLEECH = "Lait Leech"
NAMES.SHOCKWORM = "Depths Eel"


NAMES.ZASPBERRY = "Zaspberry"
NAMES.ZASPBERRY_LESSER = "Lesser Zaspberry"
NAMES.ZASPBERRY_PLANT = "Sketchy Plant"

NAMES.SNOWMONG = "Abominamole"
NAMES.MINOTAUR_BOULDER = "Ancient Stone Slab"
NAMES.MINOTAUR_BOULDER_BIG = "Giant Stone Slab"
NAMES.MINOTAUR_ORGAN = "Organ"
NAMES.MOCK_DRAGONFLY = "Wilting Dragonfly"

NAMES.MOONMAW_DRAGONFLY = "Moonmaw Dragonfly"
NAMES.MOONMAW_GLASS = "Unstable Moon Glass"
NAMES.MOONMAW_LAVAE = "Glass Lavae"
NAMES.MOONMAW_LAVAE_RING = NAMES.MOONMAW_LAVAE
NAMES.GLASS_SCALES = "Enlightened Scales"
NAMES.MOONGLASS_GEODE = "Inert Infused Moon Chunk"
NAMES.ARMOR_GLASSMAIL = "Shard-Scale Armor"
NAMES.ARMOR_GLASSMAIL_SHARDS = "Moon Shard"
NAMES.MOONMAW_TRAP = NAMES.ALTERGUARDIAN_PHASE3TRAP

NAMES.LAVAE2 = NAMES.LAVAE
NAMES.BUSHCRAB = "Bush Crab"
NAMES.ICEBOOMERANG = "Frozen Pincer"
NAMES.TOADLING = "Toadling"
NAMES.UNCOMPROMISING_TOAD = "Sickly Frog"
NAMES.TOADLINGSPAWNER = "Toad Spore"
--NAMES.NAMES.TOAD  = "Sickly Toad"
NAMES.MONSTERSMALLMEAT = "Monster Morsel"
NAMES.COOKEDMONSTERSMALLMEAT = "Cooked Monster Morsel"
NAMES.MONSTERSMALLMEAT_DRIED = "Small Monster Jerky"
NAMES.UM_MONSTEREGG = "Monster Egg"
NAMES.UM_MONSTEREGG_COOKED = "Cooked Monster Egg"
NAMES.VETERANSHRINE = "Melancholic Skull"

NAMES.WILSON_VETSKULL = "Wilson's Skull"
NAMES.WALTER_VETSKULL = "Walter's Skull"
NAMES.WORTOX_VETSKULl = "Wortox's Skull"
NAMES.MAXWELL_VETSKULL = "Maxwell's Skull"
NAMES.WILLOW_VETSKULL = "Willow's Skull"
NAMES.WARLY_VETSKULL = "Warly's Skull"
NAMES.WINKY_VETSKULL = "Winky's Skull"
NAMES.WICKERBOTTOM_VETSKULL = "Wickerbottom's Skull"
NAMES.WIXIE_VETSKULL = "Wixie's Skull"
NAMES.WOODIE_VETSKULL = "Woodie's Skull"
NAMES.WOLFGANG_VETSKULL = "Wolfgang's Skull"
NAMES.WANDA_VETSKULL = "Wanda's Skull"
NAMES.WATHGRITHR_VETSKULL = "Wigfrid's Skull"
NAMES.WES_VETSKULL = "Wes' Skull"
NAMES.WENDY_VETSKULL = "Wendy's Skull"

NAMES.UM_SHADOW_WALTER = "Walter?"
NAMES.UM_SHADOW_WORTOX = "Wortox?"
NAMES.UM_SHADOW_MAXWELL = "Maxwell?"
NAMES.UM_SHADOW_WILLOW = "Willow?"
NAMES.UM_SHADOW_WARLY = "Warly?"
NAMES.UM_SHADOW_WINKY = "Winky?"
NAMES.UM_SHADOW_WICKERBOTTOM = "Wickerbottom?"
NAMES.UM_SHADOW_WOODIE = "Woodie?"
NAMES.UM_SHADOW_WOLFGANG = "Wolfgang?"
NAMES.UM_SHADOW_WANDA = "Wanda?"
NAMES.UM_SHADOW_WATHGRITHR = "Wigfrid?"
NAMES.UM_SHADOW_WES = "Wes?"
NAMES.UM_SHADOW_WENDY = "Wendy?"

NAMES.UM_BOSS_SOUL = "Dark Soul"
NAMES.UM_DARK_VESTIGES = "Dark Vestiges"
NAMES.EXPLOSIVE_VETCURSE_SOUL = "Explosive Soul"

NAMES.UM_CHERRY_BEEQUEEN_SOUL = "Cherry Beequeen Soul"
NAMES.UM_BEEQUEEN_SOUL = "Beequeen Soul"
NAMES.UM_BEARGER_SOUL = "Bearger Soul"
NAMES.UM_DEERCLOPS_SOUL = "Deerclops Soul"
NAMES.UM_CRABKING_SOUL = "Crab King Soul"
NAMES.UM_MINOTAUR_SOUL = "Ancient Guardian Soul"
NAMES.UM_DRAGONFLY_SOUL = "Dragonfly Soul"
NAMES.UM_GOOSE_SOUL = "Goose Soul"
NAMES.UM_HOODEDWIDOW_SOUL = "Hooded Widow Soul"
NAMES.UM_KLAUS_SOUL = "Klaus Soul"
NAMES.UM_FUELWEAVER_SOUL = "Fuelweaver Soul"
NAMES.UM_MALBATROSS_SOUL = "Malbatross Soul"
NAMES.UM_MOONMAW_SOUL = "Moonmaw Soul"

NAMES.UM_RECORD_MENU = "Uncompromising Music"
NAMES.UM_RECORD_WALTER = "Follow Me, Woby!"
NAMES.UM_RECORD_WIXIE = "The Delinquent"
NAMES.UM_RECORD_SHADOW_WIXIE = "Obscuriores Sui"
NAMES.UM_RECORD_HOODED_WIDOW = "Arachnophobia"
NAMES.UM_RECORD_WATHOM = "Heart Attacked!"
NAMES.UM_RECORD_STRANGER = "A Mysterious Stranger"
NAMES.UM_RECORD_WINKY = "Funny Little Rat"
NAMES.UM_RECORD_MOONMAW = "Like A Moth to a Flame"
NAMES.UM_RECORD_TOT = "Twinsanity"

NAMES.RATSKIN = "Diseased Fur"

NAMES.PLAGUEMASK = "Plague Mask"
SKINS.ms_hat_plaguemask_formal = "Faux Plague Masque"
SKINSDESC.ms_hat_plaguemask_formal = "A fancy mask to stand out in a rotting world."

SKINS.wormwood_shadow = "The Corrupted" -- personal vendetta, bruh that shit aint 'triumphant'

NAMES.TRAPDOOR = "Inconspicuous Mound"
NAMES.SPIDER_TRAPDOOR = "Trapdoor Spider"
NAMES.SPIDER_TRAPDOOR_HOODED = "Hooded Widower"
NAMES.MUTATOR_TRAPDOOR = "Trapdoor Switcherdoodle"
NAMES.DECIDUOUS_ROOT = "Living Tree Root"
NAMES.LAVAESLIME = "Lavae Slime"
NAMES.SALTPACK = "Salt Shaker 3000"
NAMES.SPOREPACK = "Spore Pack"
NAMES.UM_BACKPACK_AMULETUSE = "Amusement Pack"
NAMES.RAT_TAIL = "Rat Tail"
NAMES.SHROOM_SKIN_FRAGMENT = "Shroom Skin Scrap"
NAMES.AIR_CONDITIONER = "Air Conditioner" --<--
NAMES.MINI_DREADEYE = "Shadow Eye"
NAMES.SHADOW_GOO = "Shadow Ink"

NAMES.ROCK_LICHEN = "Marble Melon"
NAMES.SPRINGROCK1 = "Boulder"
NAMES.SPRINGROCK2 = "Boulder"
NAMES.SPRINGROCK3 = "Boulder"

NAMES.CAVE_ENTRANCE_MAGMABIOME = "Boulder"
NAMES.CAVE_ENTRANCE_OPEN_MAGMABIOME = "Warm Sinkhole"
NAMES.CAVE_EXIT_MAGMABIOME = "Humid Stairs"
NAMES.LAVA_POND_CAVE = "Lava Pond"
NAMES.MAGMAROCK1 = "Rock"
NAMES.MAGMABONE = "Bones"

NAMES.BOULDER_CRAB = "Boulder Crab"
NAMES.BOULDER_CRAB_HOLE = "Crab Hole"
NAMES.UM_HOTSPRING = "Boiling Spring"
NAMES.VAMPIREBAT = "Adult Batilisk"
NAMES.WICKER_TENTACLE = "Sickly Tentacle"
NAMES.SKELETONMEAT = "Long Pig"
NAMES.ZASPBERRYPARFAIT = "Zaspberry Parfait"
NAMES.CARAPACECOOLER = "Carapace Cooler"
NAMES.HONEY_LOG = "Honey Log Roll"
NAMES.RNEGHOST = "Fire Stealer"
NAMES.CHIMP = "Random Chimp"
NAMES.BUGZAPPER = "Bug Zapper"
NAMES.RICE1 = "Rice Grains"
NAMES.RICE2 = "Lice Grains"
NAMES.RICE_COOKED1 = "Burnt Rice"
NAMES.RICE_COOKED2 = "Burnt Lice"
NAMES.RICEPLANT1 = "Rice"
NAMES.RICEPLANT2 = "Lice"
NAMES.SEAFOODPAELLA = "Seafood Paella"
NAMES.SWILSON = "Wilson?"
NAMES.SWATHGRITHR = "Wigfrid?"
NAMES.MOTHERGOOSE1 = "Mother Goose"
NAMES.MOTHERGOOSE2 = "Mother Moose"
NAMES.CRITTERLAB_REAL = "Rock Den"
NAMES.CRITTERLAB_REAL_BROKEN = "Broken Rock Den"
NAMES.POLLENMITES = "Pollen Mites"
NAMES.POLLENMITEDEN = "Pollen Mite Den"
NAMES.WALRUS_CAMP_SUMMER = NAMES.WALRUS_CAMP
NAMES.SUNGLASSES = "Sunglasses"
NAMES.CHARLIEPHONOGRAPH_100 = "Gramaphone"
NAMES.STUMPLING = "Pineling"
NAMES.BIRCHLING = "Birchling"
NAMES.LICELOAF1 = "Liceloaf"
NAMES.LICELOAF1 = "Riceloaf"
NAMES.MOON_TEAR = "Moon Tear"
NAMES.SHADOW_TELEPORTER = "Grasping Shadow"
NAMES.WAXWELL_PACT_TRADER = "Pact Maker"

NAMES.SHADOW_CROWN = "Shadow Crown"
NAMES.UM_SHADOW_AXE = "Gloom Cutter"
NAMES.CALIFORNIAKING = "California King"
NAMES.TRAPDOORGRASS = "Wide Grass"
NAMES.LUREPLAGUE_RAT = "Lureplague Rat"
NAMES.SNAPPERTURTLE = "Snapper Turtle"
NAMES.SNAPPERTURTLEBABY = "Whippersnapper Turtle"
NAMES.SNAPPERTURTLENEST = "Nest"

NAMES.CURSED_ANTLER = "Cursed Antler"
SKINS.ms_twisted_antler = "Twisted Antler"
SKINSDESC.ms_twisted_antler = "A twisted antler for a twisted person."

NAMES.CRYSTAL_CURSED_ANTLER = "Crystal Cursed Antler"

NAMES.UM_EXHUMER = "Exhumer"
NAMES.UM_WINGSUIT = "Wingsuit"
NAMES.UM_MOONFLY_LANTERN = "Moonfly Lantern"

NAMES.MARSH_GRASS = "Marsh Bush"
NAMES.GIANT_TREE = "Giant Redwood"
NAMES.WEBBEDCREATURE = "Silky Cocoon"
NAMES.WIDOWSGRASP = "Widow's Claw"
NAMES.HOODEDWIDOW = "Hooded Widow"
NAMES.SILKSACK = "Silken Sack"
NAMES.SILKEN_BUNDLE = "Webbed Supplies"


NAMES.WEBBEDCREATURE_BUGGY = "Buggy Cocoon"
NAMES.WEBBEDCREATURE_GROSS = "Grotesque Cocoon"
NAMES.WEBBEDCREATURE_HAIRY = "Hairy Cocoon"
NAMES.WEBBEDCREATURE_HARD = "Hardened Cocoon"
NAMES.WEBBEDCREATURE_LEATHER = "Leathery Cocoon"
NAMES.WEBBEDCREATURE_FEATHER = "Feathery Cocoon"
NAMES.WEBBEDCREATURE_LEAFY = "Leafy Cocoon"

NAMES.GIANT_BLUEBERRY = "Boomberry"
NAMES.BLUEBERRYPLANT = "Boomberry Plant"
NAMES.BLUEBERRYFLOWER = "Boomberry Flower"
NAMES.HOODEDTRAPDOOR = "Flat Stone"
NAMES.HOODED_FERN = "Thicket"
NAMES.FALLINGBEEHIVE = NAMES.BEEHIVE
NAMES.FRUITBAT = "Fruit Bat"
NAMES.PITCHERPLANT = "Pitcherplant"

NAMES.DEPLETED_HOODED_FERN = "Large Fern"
NAMES.APHID = "Aphid"
NAMES.NYMPH = "Nymph"
NAMES.WIDOWSHEAD = "Widow's Head"
NAMES.CCTRINKET_DON = "Torn Book"
NAMES.CCTRINKET_JAZZY = "Rusty Saxophone"
NAMES.CCTRINKET_FREDDO = "Broken Cassete"
NAMES.CCTRINKET_NAMES = "Needed Nametag"

NAMES.BLUEBERRYPANCAKES = "Boomberry Pancakes"
NAMES.DEVILSFRUITCAKE = "Devils Fruit Cake"
NAMES.SIMPSALAD = "Simple Salad"
NAMES.BEEFALOWINGS = "Beefalo Wings"
NAMES.PINEPILE = "Needle Pile"
NAMES.HOODED_MUSHTREE_TALL = NAMES.MUSHTREE_TALL
NAMES.HOODED_MUSHTREE_MEDIUM = NAMES.MUSHTREE_MEDIUM
NAMES.HOODED_MUSHTREE_SMALL = NAMES.MUSHTREE_SMALL
NAMES.SCREECHER_TRINKET = "Lost Doll"
NAMES.SNOWCONE = "Snowcone"
NAMES.WATERMELON_LANTERN = "Watermelon Lantern"
NAMES.ANCIENT_TREPIDATION = "Trepidation"
NAMES.ANCIENT_TREPIDATION_ARM = "Trepidation's Reach"
NAMES.STEEL_SWEATER = "Steel Sweater"
NAMES.RNESKELETON = "Skeleton"

NAMES.ANCIENT_AMULET_RED = "Ancient Soul Amulet"
SKINS.ms_ancient_amulet_red_demoneye = "Demon-eyed Amulet"
SKINSDESC.ms_ancient_amulet_red = "" --TODO

NAMES.RAT_WHIP = "Tail o' Twined Rats"
NAMES.KLAUS_AMULET = "Naught Lock"
NAMES.HOUND_LIGHTNING = "Supercharged Lightning"
NAMES.LIGHTNINGHOUND = "Lightning Hound"
NAMES.MAGMAHOUND = "Magma Varglet"
NAMES.SPOREHOUND = "Spore Hound"
NAMES.GLACIALHOUND = "Glacial Varglet"
NAMES.CRABCLAW = "Crab Claw"
NAMES.BIGHT = "Comingled Clockwork"
NAMES.KNOOK = "Automaton Abomination"
NAMES.ROSHIP = "Mechanical Monstrosity"
NAMES.SNOTROAST = "Snot Roast"
NAMES.LICELOAF = "Liceloaf" --For the cookbook

NAMES.TURF_HOODEDMOSS = "Mossy Forest Turf"
NAMES.TURF_HOODEDFOLIAGE = "Undergrowth Turf"
NAMES.TURF_HOODEDFOLIAGE_DARK = "Dark Undergrowth Turf"

NAMES.TURF_ANCIENTHOODEDTURF = "Ancient Hooded Turf"
NAMES.TURF_UM_HOTSPRING_GRASS = "Mucky Forest Turf"
NAMES.TURF_UM_HOTSPRING_YELLOWROCK = "Yellow Rock Turf"
NAMES.TURF_UM_HOTSPRING_WHITEROCK = "White Rock Turf"
NAMES.TURF_UM_MAGMA = "Magmatic Rock Turf"
NAMES.TURF_MAGMA_GRASS = "Pyre Grass Turf"

NAMES.DEERCLOPS_BARRIER = "Glacial Wall"
NAMES.PIGKING_PIGTORCH = NAMES.PIGTORCH
NAMES.UM_PAWN = "Clockwork Pawn"
NAMES.UM_PAWN_NIGHTMARE = "Damaged Clockwork Pawn"
NAMES.CAVE_ENTRANCE_SUNKDECID = NAMES.CAVE_ENTRANCE
NAMES.CAVE_ENTRANCE_OPEN_SUNKDECID = NAMES.CAVE_ENTRANCE_OPEN
NAMES.CAVE_EXIT_SUNKDECID = NAMES.CAVE_EXIT
NAMES.CAVE_ENTRANCE_MOON = NAMES.CAVE_ENTRANCE
NAMES.CAVE_ENTRANCE_OPEN_MOON = NAMES.CAVE_ENTRANCE_OPEN
NAMES.CAVE_EXIT_MOON = NAMES.CAVE_EXIT
NAMES.GORE_HORN_HAT = "Gore Horn"
NAMES.SLOBBERLOBBER = "Slobber Lobber"
NAMES.BEARGERCLAW = "Bearger Claw"
NAMES.LAVASPIT_SLOBBER = NAMES.LAVASPIT
NAMES.WOODPECKER = "Woodpecker"
NAMES.UM_BEAR_TRAP = "Snap-Trap"
NAMES.UM_BEAR_TRAP_OLD = "Snap-Trap"
NAMES.MOTHERMOSSLING = NAMES.MOSSLING
NAMES.MOTHERMOOSEEGG1 = "Golden Moose Egg"
NAMES.MOTHERMOOSEEGG2 = "Golden Goose Egg"
NAMES.CORNCAN = "Canned Corn"
NAMES.SKULLCHEST_CHILD = "Skull Chest"
NAMES.SKULLCHEST = "Skull Chest"
NAMES.GREENFOLIAGE = "Hooded Foliage" --Well, I guess I did this then...

NAMES.FEATHER_FROCK = "Feather Frock"
SKINS.ms_feather_frock_fancy = "Raven Cloak"
SKINSDESC.ms_feather_frock_fancy = "A fancy cloak made out of the finest feathers."

NAMES.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "Snap-Teeth"
NAMES.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "Shiny Snap-Teeth"
NAMES.DRIFTWOODFISHINGROD = "Driftwood Fishing Rod"

NAMES.REDGEM_CRACKED = "Shaped Red Gem"
NAMES.BLUEGEM_CRACKED = "Shaped Blue Gem"
NAMES.ORANGEGEM_CRACKED = "Shaped Orange Gem"
NAMES.GREENGEM_CRACKED = "Shaped Green Gem"
NAMES.YELLOWGEM_CRACKED = "Shaped Yellow Gem"
NAMES.PURPLEGEM_CRACKED = "Shaped Purple Gem"
NAMES.OPALPRECIOUSGEM_CRACKED = "Shaped Iridescent Gem"
NAMES.RED_MUSHED_ROOM = "Red Mushed-Room"
NAMES.GREEN_MUSHED_ROOM = "Green Mushed-Room"
NAMES.BLUE_MUSHED_ROOM = "Blue Mushed-Room"

--Stanton's Stash
NAMES.STANTON_SHADOW_TONIC = "Shadow Tonic"
NAMES.STANTON_SHADOW_TONIC2 = NAMES.STANTON_SHADOW_TONIC
NAMES.STANTON = "Skelton Cree"
NAMES.SKULLFLASK = "Skull Flask"
NAMES.SKULLFLASK_EMPTY = "Empty Skull Flask"
--Stanton's Stash

NAMES.THEATERCORN = "Theater Corn"
NAMES.ARMORLAVAE = "Dimvae"
NAMES.WIDOW_WEB_COMBAT = "Sticky Webbing"

NAMES.BOOK_RAIN_UM = "Rainy Days"

NAMES.RAIN_HORN = "Drowning Conch"
NAMES.FLORAL_BANDAGE = "Sweetflower Wrap"
NAMES.DORMANT_RAIN_HORN = "Dormant Conch"

NAMES.NIGHTCRAWLER = "Night Crawler"
NAMES.UM_NIGHTCRAWLER = "Night Crawler"
NAMES.RNE_GRABBYSHADOWS = "Grasping Fear"
NAMES.NERVOUSTICK = "Nervous Tick"
NAMES.NERVOUSTICKDEN = "Heart of the Swarm"
NAMES.FUELSEEKER = "Fuel Seeker"
NAMES.MINDWEAVER = "Mind Weaver"
NAMES.UM_HECKLER = "Ms. Spitts"

NAMES.RNEMUSHROOMBOMB = "Boomshroom"

NAMES.HAT_BAGMASK = "Paper Bag"
NAMES.HAT_BLACKCATMASK = "Black Cat Mask"
NAMES.HAT_CLOWNMASK = "Clown Mask"
NAMES.HAT_WATHOMMASK = "Creature Mask"
NAMES.HAT_DEVILMASK = "Devil Mask"
NAMES.HAT_FIENDMASK = "Fiend Mask"
NAMES.HAT_GHOSTMASK = "Ghost Mask"
NAMES.HAT_GLOBMASK = "Glob Mask"
NAMES.HAT_HOCKEYMASK = "Hockey Mask"
NAMES.HAT_JOYOUSMASK = "Joyous Mask"
NAMES.HAT_MERMMASK = "Merm Mask"
NAMES.HAT_OOZEMASK = "Ooze Mask"
NAMES.HAT_ORANGECATMASK = "Orange Cat Mask"
NAMES.HAT_PHANTOMMASK = "Phantom Mask"
NAMES.HAT_PIGMASK = "Pig Mask"
NAMES.HAT_PUMPGOREMASK = "Pumpgore Mask"
NAMES.HAT_REDSKULLMASK = "Red Skull Mask"
NAMES.HAT_SKULLMASK = "Skull Mask"
NAMES.HAT_SPECTREMASK = "Spectre Mask"
NAMES.HAT_WHITECATMASK = "White Cat Mask"
NAMES.HAT_TECHNOMASK = "Techno-Tronic Mask"
NAMES.HAT_MANDRAKEMASK = "Mandrake Mask"
NAMES.HAT_OPOSSUMMASK = "Opossum Mask"
NAMES.RNE_GOODIEBAG = "Goodie Bag"
NAMES.HAT_RATMASK = "Rat Mask"

NAMES.OCULET = "Oculet"
NAMES.OCULET_REZ = "Rez"
NAMES.OCULET_SPAZ = "Spaz"
NAMES.WILLIAM = "William"

--Under the Weather--
NAMES.UNCOMPROMISING_HARPOON = "Harpoon"
NAMES.UNCOMPROMISING_HARPOON_HEAVY = "Heavy Harpoon"
NAMES.UNCOMPROMISING_HARPOONREEL = "Reel"
NAMES.UM_MAGNERANG = "Magnerang"
NAMES.UM_MAGNERANGREEL = "Magnerang Magnet"
NAMES.UNCOMPROMISING_FISHINGNET = "Fishing Net"
NAMES.UM_BEEGUN = "Hand Held Hive"
NAMES.UM_BEEGUN_CHERRY = "Hand Held Hibeescus Hive"
NAMES.BULLETBEE = "Bullet Bee"
NAMES.CHERRYBULLETBEE = "Bullet Hibeescus"
NAMES.UM_BULLETBEE_PROJ = "Bullet Bee"
NAMES.UM_CHERRYBULLETBEE_PROJ = "Bullet Hibeescus"

NAMES.WINONA_TOOLBOX = "Contraption Container"
NAMES.OCEAN_SPEAKER = "Dilapidated Speaker" --Kinda lame dunno what else though.
NAMES.OCEAN_SPEAKER_TEASER = NAMES.OCEAN_SPEAKER
NAMES.SUNKENCHEST_ROYAL_RANDOM = "Royal Sunken Chest"

NAMES.SUNKENCHEST_ROYAL_RED = "Gem Encrusted Chest"
NAMES.SUNKENCHEST_ROYAL_BLUE = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_PURPLE = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_GREEN = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_ORANGE = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_YELLOW = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_RAINBOW = "Prismatic " .. NAMES.SUNKENCHEST_ROYAL_RED

NAMES.SLUDGE = "Sea Sludge"
NAMES.SLUDGE_OIL = "Sulfur Extract"
NAMES.BOATPATCH_SLUDGE = "Driftwood Boat Corks"
NAMES.SLUDGESTACK = "Thermal Vent"
NAMES.SLUDGE_SACK = "Sludge Sack"

NAMES.ARMOR_REED_UM = "Reed Suit"
NAMES.ARMOR_SHARKSUIT_UM = "Rock Hide Armor"

NAMES.ROCKJAWLEATHER = "Rocky Hide"

NAMES.LANTERN_ELECTRICAL = "Electrical Lantern"
NAMES.MINERHAT_ELECTRICAL = "Electrical Miner Hat"

NAMES.POWERCELL = "Energy Cell" --Single-Use Battery

NAMES.SEAROCK_RING = "Sea Stack"
NAMES.RR_POWERLINE = "Powerline"
NAMES.EYEOFTERROR_MINI_ALLY = "Hardy Peeper"
NAMES.EYEOFTERROR_MINI_GROUNDED_ALLY = "Hardy \"Egg\""
NAMES.STUFFED_PEEPER_POPPERS = "Stuffed Peeper Poppers"
NAMES.UM_DEVILED_EGGS = "Deviled Eggs"
NAMES.SIREN_BIRD_NEST = "Nested Sea Stack"
NAMES.SIREN_BIRD_NEST_TEASER = NAMES.SIREN_BIRD_NEST
NAMES.SIREN_THRONE = "Sirens Throne"
NAMES.SIREN_THRONE_TEASER = NAMES.SIREN_THRONE
--NAMES.NAMES.UM_SIREN = "Siren"
NAMES.WINONA_UPGRADEKIT_ELECTRICAL = "Electrical Conversion Kit"
NAMES.UM_SORREL = "Sorrel"

NAMES.CRITTER_FIGGY = "Figgy"
NAMES.CRITTER_FIGGY_BUILDER = "Figgy"

NAMES.PORTABLEBOAT_ITEM = "Portable Raft"
NAMES.PORTABLEBOAT_RIPCORD = "Portable Raft Plug"

NAMES.MASTUPGRADE_WINDTURBINE_ITEM = "Wind Turbine"

NAMES.LUSH_ENTRANCE = "Overly Ominous Hole"
NAMES.GIANT_TREE_BIRDNEST = "Nest"

NAMES.CANNONBALL_SLUDGE_ITEM = "Crude Cannonball"
NAMES.CANNONBALL_SLUDGE = "Crude Cannonball"
NAMES.UM_COPPER_PIPE = "Copper Pipes"
NAMES.STEERINGWHEEL_COPPER = "Copper Steering Wheel"
NAMES.STEERINGWHEEL_COPPER_ITEM = "Copper Steering Wheel Kit"
NAMES.BOAT_BUMPER_SLUDGE = "Sludge Bumper"
NAMES.BOAT_BUMPER_SLUDGE_KIT = "Sludge Bumper Kit"
NAMES.BOAT_BUMPER_COPPER = "Copper Bumper"
NAMES.BOAT_BUMPER_COPPER_KIT = "Copper Bumper Kit"
NAMES.HERMIT_BUNDLE_LURES = "Lure Bundle"
NAMES.LAVASPIT_SLUDGE = "Burning Pool of Sludge"

NAMES.KELPSTACK = "Kelpy Seastack"
NAMES.MOSSSTACK = "Mossy Seastack"

NAMES.SPECTER_SHIPWRECK = "Abandoned Shipwreck"
NAMES.UM_DREAMCATCHER = "Dream Catcher"
NAMES.UM_BRINEISHMOSS = "Brineish Moss"
NAMES.UM_COALESCED_NIGHTMARE = "Coalesced Nightmare"
NAMES.BRINE_BALM = "Brine Balm"
NAMES.SLUDGE_CORK = "Sludge Plug"
NAMES.UM_SPECTOPLASM = "Spectoplasm"
NAMES.UM_SPECTER_AMULET = "Specter Amulet"
NAMES.PHANTOM = "Phantom" --phantom like minecraft :-O
NAMES.UMSS_GENERAL = "UMSS"
NAMES.UM_DEVCAPTURE = "Devcapture Device"
NAMES.UM_BEEGUARD_SEEKER = "Bomber Bee"
NAMES.UM_BEEGUARD_BLOCKER = "Blocker Bee"
NAMES.UM_BEEGUARD_SHOOTER = "Bullet Bee"

NAMES.UM_ORNAMENT_OPOSSUM = "Opossum Decoration"
NAMES.UM_ORNAMENT_RAT = "Rat Decoration"

NAMES.TRINKET_WATHOM1 = "Busted Inhaler"

NAMES.DEATHAMP = "a heart attack"

NAMES.CODEX_MANTRA = "Codex Mantra"
NAMES.SHADOWVORTEX = "Shadow Vortex"

NAMES.UM_INKUBATOR = "Ancient Inkubator"
NAMES.UM_SCRAPPER = "Ancient Scrapper"
NAMES.UM_ASTRAL_PROJECTOR = "Astral Projectinator"
NAMES.UM_ASTRAL_PROJECTOR_TARGET = "Astral Receptionator"

NAMES.UM_MEAT_CUBE = "Meat Cube"
NAMES.UM_MONSTER_CUBE = "Monster Cube"
NAMES.UM_VEGGIE_CUBE = "Veggie Cube"
NAMES.UM_SUGAR_CUBE = "Sugar Cube"
NAMES.UM_ROUGHAGE_CUBE = "Wooden Cube"
NAMES.UM_BLAND_CUBE = "Bland Cube"

--Ocupus Parts
NAMES.UM_OCUPUS_EYE = "Eye Stalk"
NAMES.UM_OCUPUS_EYETACLE = "Eye Stalk"
NAMES.UM_OCUPUS_TENTACLE = "Tentacle"
NAMES.UM_OCUPUS_BEAK = "Beak"

--Ocupus Items
NAMES.OCUPUS_TENTACLE = "Ocupus Tentacle"
NAMES.OCUPUS_TENTACLE_EYE = "Ocupus Eye"
NAMES.OCUPUS_TENTACLE_COOKED = "Cooked Tentacle"
NAMES.OCUPUS_BEAK = "Ocupus Beak"
NAMES.BEAKBASHER = "Beak Basher"
NAMES.PLAUNT_MANNY = "Houndious Observious"

-- WIXIE & WALTER RELATED STRINGS

NAMES.WIXIE_PIANO = "Grand Piano"
NAMES.WIXIE_PIANO_CARD = "Mysterious Paper"
NAMES.WIXIE_CLOCK = "Grandfather Clock"
NAMES.WIXIE_CLOCKDANGLEY1 = "Seconds Weight"
NAMES.WIXIE_CLOCKDANGLEY2 = "Minutes Weight"
NAMES.WIXIE_CLOCKDANGLEY3 = "Hours Weight"
NAMES.WIXIE_WARDROBE = "Fancy Wardrobe"
NAMES.CHARLES_T_HORSE = "Broken Toy"
NAMES.THE_REAL_CHARLES_T_HORSE = "Charles T. Horse"
NAMES.WOODEN_QUEEN_PIECE = "Wooden Queen"
NAMES.WIXIE_SHADOWCLONE = "Wixie?"
NAMES.SHADOW_WIXIE = "Wixie?"
NAMES.WIXIE_SHADOW_CLONE = "Wixie?"
NAMES.SHADOW_WIXIE_HELPER = "Wixie?"

NAMES.SLINGSHOT_MATILDA = "Matilda"
NAMES.SLINGSHOT_GNASHER = "Gnasher"
NAMES.SLINGSHOT_JESSIE = "Jessie"
NAMES.SLINGSHOT_CLAIRE = "Claire"

NAMES.SLINGSHOTAMMO_LAZY = "Lazy Prankster Rounds"
NAMES.SLINGSHOTAMMO_SHADOW = "Nightmare Rounds"
NAMES.SLINGSHOTAMMO_FIRECRACKERS = "Firecracker Rounds"
NAMES.SLINGSHOTAMMO_HONEY = "Honey Rounds"
NAMES.SLINGSHOTAMMO_RUBBER = "Rubberband Rounds"
NAMES.SLINGSHOTAMMO_TREMOR = "Tremor Rounds"
NAMES.SLINGSHOTAMMO_MOONROCK = "Moonphase Rounds"
NAMES.SLINGSHOTAMMO_MOONGLASS = "Moon Shard Rounds"
NAMES.SLINGSHOTAMMO_SALT = "Salty Rounds"
NAMES.SLINGSHOTAMMO_SLIME = "Slimey Rounds"
NAMES.SLINGSHOTAMMO_GOOP = "Gloop Rounds"
NAMES.SLINGSHOTAMMO_FLARE = "Flare Rounds"

NAMES.SLINGSHOTAMMO_INSANITY = "Insanity Rounds"
NAMES.SLINGSHOTAMMO_LUNARVINE = "Lunarvine Rounds"

NAMES.BAGOFMARBLES = "Bag O' Marbles"

NAMES.SLINGSHOTAMMO_LIMESTONE = "Crust Cookie Rounds"
NAMES.SLINGSHOTAMMO_TAR = "Stick-a-Rounds"
NAMES.SLINGSHOTAMMO_OBSIDIAN = "Obsidian Rounds"

NAMES.PLACEHOLDER_INGREDIENT_IA_UM = "Requires Island Adventures or Uncompromising Mode!"
NAMES.PLACEHOLDER_INGREDIENT_IA = "Requires Island Adventures!"

NAMES.MEATRACK_HAT = "Jerky Hat"

NAMES.WIXIEGUN =
"The Glock 17 (Beretta 92FS in the HD Edition), also known as the 9mm Pistol, is a weapon featured in Half-Life and its expansions."

NAMES.UM_MAXWELL_ARMOR_SANITY = "Magician's Night Armor"
NAMES.UM_MAXWELL_NIGHTSWORD = "Magician's Dark Sword"
--NAMES.PACT_ARMOR_SANITY = "Shadow Pact Armor"
--NAMES.PACT_SWORD_SANITY = "Shadow Pact Sword"
------------------------

NAMES.WINONA_CATAPULT_ITEM_UM = "Dismantled " .. NAMES.WINONA_CATAPULT
NAMES.WINONA_SPOTLIGHT_ITEM_UM = "Packed " .. NAMES.WINONA_SPOTLIGHT
NAMES.WINONA_BATTERY_LOW_ITEM_UM = "Dissasembled " .. NAMES.WINONA_BATTERY_LOW
NAMES.WINONA_BATTERY_HIGH_ITEM_UM = NAMES.WINONA_BATTERY_HIGH .. " Parts"

NAMES.STAFF_STARFALL = "Starfall Staff"
NAMES.STAFF_MOONFALL = "Moonfall Staff"
NAMES.MOONFALL_PROJ = "Shooting Star"
NAMES.HAT_CRAB = "Crab Crown"
NAMES.HAT_CRAB_ICE = "Frigid Crown"
NAMES.KALEIDOSCOPE = "Kaleidoscope"
NAMES.MOONGLOW = "Moonglow"
NAMES.ARMOR_CRAB_MAXHP = "Gem Encrusted Shell Armor"
NAMES.ARMOR_CRAB_REGEN = "Healing Rock Armor"
NAMES.MOON_BEACON_KIT = "Inactive Moon Beacon"
NAMES.MOON_BEACON = "Moon Beacon"

NAMES.MARA_BOSS1 = "Sans Undertale From The Hit Series Super Smash Brothers (Featuring Minecraft Steve) [& Knuckles]"
NAMES.MARA_BOSS1_BULLETS = "a bad time"
NAMES.UM_WITCH = "Supreme Calamitas"

-- Pyre Nettle stuff
NAMES.UM_PYRE_NETTLES = "Pyre Nettles"
NAMES.UM_SMOLDER_SPORE = "Smolder Spore"
NAMES.UM_ARMOR_PYRE_NETTLES = "Pyre Mantle"
NAMES.UM_BLOWDART_PYRE = "Pyre Dart"

-- Mutation Extrapolation
NAMES.UMDEBUFF_MOONBURN = "a moonburn"
NAMES.UMDEBUFF_MOONBURN_TESTINGSTICK = "Magic Pain Stick"

-- Under the Weather Part 1
NAMES.ALPHA_LIGHTNINGGOAT = "Alpha Volt Goat"
NAMES.UM_TORNADO = "Giant Tornado"
NAMES.UM_WATERFALL = "Waterfall"
NAMES.PORTABLEBOAT = "Portable Raft"

NAMES.UM_WINDTURBINE = "Wind Turbine"
NAMES.MASTUPGRADE_WINDTURBINE = "Wind Turbine"

NAMES.GARBAGEPATCHFLOTSAM = "Storm Debris"

NAMES.PIGKING_PIGGUARD = NAMES.PIGGUARD

NAMES.UM_BOAT_ENGINE = "Sludge Engine"
NAMES.SMOG = "suffocation"

------------------------
-- Broiling Hills --
------------------------
NAMES.SNAILDRAKE_EXPLOSION = "Snaildrake Explosion"
NAMES.SNAILDRAKE_HOLE = "Crevasse"
NAMES.SNAILDRAKE_MAGMA = "Snaildrake"
NAMES.SNAILDRAKE_SLIME = "Snaildrake"
NAMES.SNAILDRAKE_MAGMA_SLUDGE = "Magma Sludge"
NAMES.SNAPALM = "Snapalm"
NAMES.SNAILDRAKEHAT = "Snaily Horned Helm"
NAMES.SNAILDRAKEBUCKET = "Snaildrake Basin"

------------------------
-- Magma Caves --
------------------------
NAMES.MUSHTREE_SHADOW = "Gloom Shroom"
NAMES.GLOOMCAP = "Dusk Cap"
NAMES.GLOOMCAP_COOKED = "Cooked Dusk Cap"
NAMES.SPORE_SHADOW = "Dusk Spore"
NAMES.VIPERWORM = "Depths Viper"
NAMES.VIPERLING = "Writhing Apparition"
NAMES.VIPERLINGFRIEND = "Writhing Apparition"
NAMES.VIPERFRUIT = "Gloomberry"
NAMES.VIPERFRUIT_LESSER = "Lesser Gloomberry"
NAMES.VIPERJAM = "Gloomberry Jam"
NAMES.VIPERFRUIT_PLANT = "Ominous Plant"
NAMES.UM_GHOST_PEPPER = "Faded Vine"
NAMES.UM_GHOST_PEPPER_ITEM = "Ghost Pepper"
------------------------
-- Rimeweed --
------------------------
NAMES.RIMEWEED_MAIN = "Spiny Rimeweed"
NAMES.RIMEWEED_BARRIER = "Rimeweed Bramble"
NAMES.RIMEWEED_WHIP = "Rime Lash"
NAMES.UM_RIMEWEED_ITEMFLOWER = "Rime Flower"
NAMES.UM_RIMEWEED_ITEMVINE = "Frosty Vine"
NAMES.UM_RIMEWEED_SPAGETT = "Spaghetti Cryonara"
NAMES.UM_RIMEWEED_TEQUILA = "Chillquilla"
NAMES.UM_RIMEWEED_ICEPACK = "Ice Pack"
NAMES.UM_BLOWDART_RIME = "Rime Dart"
NAMES.UM_ARMOR_BRAMBLE_RIMEWEED = "Rime Husk"
NAMES.UM_HAT_RIME = "Normong Helmet"
NAMES.UM_ICE_TAIL = "Frozen Mole Tail"

NAMES.UM_DURIAN_CREAM_MARSHCAKE = "Durian Cream Marshcake"
NAMES.UM_CHILES_EN_NOGADA = "Chiles en Nogada"
NAMES.UM_RICE_PUDDING = "Rice Pudding"
NAMES.UM_KEBAB = "Boneless Kebab"


NAMES.UM_COOKPOT_WAGSTAFF = "POT-800"
NAMES.UM_COOKPOT_WAGSTAFF_DISPLAY = "Intriguing Display"
NAMES.UM_COOKPOT_WAGSTAFF_LEVER = "Scrappy Lever"
NAMES.UM_COOKPOT_WAGSTAFF_LEVER2 = "Junky Lever"

NAMES.STAFF_TORNADO_LIGHTNING = "Empowered Weather Pain"
NAMES.RNEHOUND = "Umbral Hound"

NAMES.JAWED_SCYTHE = "Jawed Scythe"
NAMES.UM_ICE_SICLE = "Ice Sickle"
NAMES.SNAPPY_JAW = "Snappy Jaw"
NAMES.UM_BOATBOTTLE = "Boat Bottle"
NAMES.BOAT_ANCIENT_ITEM_BLUEPRINT = "Archaic Boat Kit Blueprint"
NAMES.UM_BUTTERY_FLY = "Buttery Fly"
NAMES.UM_HAT_LEAFWING = "Elated Helm"
NAMES.UM_LEAFWING = "Leafy Wing"
NAMES.UM_DETONATOR = "Universal Detonator"

NAMES.UM_BEE_MOON = "Carrion Bee"
NAMES.UM_BEEHIVE_MOON = "Carrion Bee Hive"
NAMES.UM_MEATCOMB = "Carrion Honeycomb"
NAMES.UM_MEATHONEY = "Carrion Honey"

NAMES.FYRITEROCK = "Pyrite Outcropping"
NAMES.UM_FYRITE = "Pyrite"
NAMES.UM_FYRE_BOMB = "Pyre Bomb"
NAMES.UM_MANNY = "Plaunt Manny"

NAMES.UM_HAT_BEE_MOON = "Beeret"
NAMES.UM_EYEBALM = "Eye Balm"
NAMES.UM_BEEMINE_MOON = "Carrion Bee Mine"
NAMES.UM_BEEMINE_MOON_ITEM = "Carrion Bee Mine"

NAMES.UM_PLANT_HOTSPRINGS = "Plant"
NAMES.UM_PEPPERDRAGON_NEST = "Capsidragon Nest"

NAMES.UM_GHOST_FAJITA = "Ghastly Fajita"
NAMES.UM_BOOM_TART = "Boomberry Tart"
NAMES.UM_RIBOPOD = "Ribopod"
NAMES.UM_RIBOPODDEN = "Bone Mound"

NAMES.UM_GEMOLOGYGEM_UNKNOWN = {
    DEFAULT = "Strange Gem",
    RED = "Strange Red Gem",
    ORANGE = "Strange Orange Gem",
    YELLOW = "Strange Yellow Gem",
    GREEN = "Strange Green Gem",
    BLUE = "Strange Blue Gem",
    PURPLE = "Strange Purple Gem",
    PALE = "Strange Pale Gem"
}


NAMES.UM_GEMOLOGYGEM_PREFIX = {
    "Cracked",
    "Rough",
    "Flawless"
}

NAMES.UM_GEMOLOGYBLUEGEM1 = "Arctic Aquamarine"
NAMES.UM_GEMOLOGYBLUEGEM2 = "Chilled Sapphire"
NAMES.UM_GEMOLOGYREDGEM1 = "Voracious Ruby"
NAMES.UM_GEMOLOGYREDGEM2 = "Passionate Garnet"
NAMES.UM_GEMOLOGYPURPLEGEM1 = "Furious Fluorite"
NAMES.UM_GEMOLOGYPURPLEGEM2 = "Arcane Amethyst"
NAMES.UM_GEMOLOGYYELLOWGEM1 = "Hasty Topaz"
NAMES.UM_GEMOLOGYYELLOWGEM2 = "Static Amber"
NAMES.UM_GEMOLOGYGREENGEM1 = "Neurotic Peridot"
NAMES.UM_GEMOLOGYGREENGEM2 = "Chaotic Emerald"
NAMES.UM_GEMOLOGYORANGEGEM1 = "Comfy Zircon"
NAMES.UM_GEMOLOGYORANGEGEM2 = "Hoarding Citrine"
NAMES.UM_GEMOLOGYPALEGEM1 = "Peerless Jade"
NAMES.UM_GEMOLOGYPALEGEM2 = "Adamant Diamond"
NAMES.UM_GEMOLOGYFORGE = "Ancient Gemstone Forge"

NAMES.GEMTOOL_PREFIX = {
    UM_GEMOLOGYGREENGEM1 = "Neurotic",
    UM_GEMOLOGYGREENGEM2 = "Chaotic",
    UM_GEMOLOGYYELLOWGEM1 = "Hasty",
    UM_GEMOLOGYYELLOWGEM2 = "Static",
    UM_GEMOLOGYPALEGEM1 = "Peerless",
    UM_GEMOLOGYPALEGEM2 = "Adamant",
    UM_GEMOLOGYREDGEM1 = "Voracious",
    UM_GEMOLOGYREDGEM2 = "Passionate",
    UM_GEMOLOGYPURPLEGEM1 = "Furious",
    UM_GEMOLOGYPURPLEGEM2 = "Arcane", 
    UM_GEMOLOGYORANGEGEM1 = "Comfy",
    UM_GEMOLOGYORANGEGEM2 = "Hoarding",
    UM_GEMOLOGYBLUEGEM1 = "Arctic",
    UM_GEMOLOGYBLUEGEM2 = "Chilled",
}

NAMES.WATHOM_CORPSE = "Wathom's Carapace"

NAMES.UM_SPONGEPLANT = "Swiss Sponge"
NAMES.UM_SPONGEPLANT_ITEM = "Swiss Sponge Chunks"
NAMES.UM_SPONGE_CAKE = "Swiss Sponge Cake"

NAMES.UM_MOSS = "Hooded Moss"

NAMES.WATHGRITHR_SHIELD_DREADSTONE = "Dread Rönd"
NAMES.UM_FERN_FOX = "Ferned Fox"
NAMES.UM_FERN_FOX_DEN = "Fox Hole"

NAMES.UM_PEPPERDRAGON = "Capsidragon"
NAMES.UM_PEPPERDRAGON_BLADDER = "Fire Bladder"
NAMES.UM_FLAMETHROWER = "Flame Burster"
NAMES.UM_FIRECREAM = "Flame Repellent"
NAMES.UM_HAT_PEPPERDRAGON = "Capsi Cap"

NAMES.UM_GEMOLOGY_GEODE_RED = "Red Fungal Geode"
NAMES.UM_GEMOLOGY_GEODE_GREEN = "Green Fungal Geode"
NAMES.UM_GEMOLOGY_GEODE_BLUE = "Blue Fungal Geode"
NAMES.UM_GEMOLOGY_GEODE_GUANO = "Fecal Geode"
NAMES.UM_GEMOLOGY_GEODE_LOBSTER = "Fetal Geode"
NAMES.UM_GEMOLOGY_GEODE_GLASS = "Glass Geode"
NAMES.UM_GEMOLOGY_GEODE_SLIME = "Slimy Geode"
NAMES.UM_GEMOLOGY_GEODE_RUINS = "Junk Geode"
NAMES.UM_GEMOLOGY_GEODE_VENT = "Pumice Geode"
NAMES.UM_GEMOLOGY_GEODE_SINK = "Mossy Geode"

NAMES.UM_BOOMBERRY_BOMB = "Boomberry Bomb"
NAMES.UM_BOOMBERRYPIE = "Boomberry Pie"

NAMES.UM_REDMUSHTREE_GEM = "Petrified Mushtree"
NAMES.UM_REDMUSHTREE_GEMLESS = "Petrified Mushtree"
NAMES.UM_GREENMUSHTREE_GEM = "Petrified Mushtree"
NAMES.UM_GREENMUSHTREE_GEMLESS = "Petrified Mushtree"
NAMES.UM_BLUEMUSHTREE_GEM = "Petrified Mushtree"
NAMES.UM_BLUEMUSHTREE_GEMLESS = "Petrified Mushtree"

NAMES.UM_GUANO_ROCK = "Coprolite Outcrop"
NAMES.UM_GUANO_ROCK_GEMLESS = "Coprolite Outcrop"
NAMES.UM_SLIMESTONE_ROCK_GEMLESS = "Slimestone"
NAMES.UM_SLIMESTONE_ROCK = "Slimestone"
NAMES.UM_ROCKLOBSTER_ROCK = "Gestating Rock"
NAMES.UM_SINKMOUND_ROCK = "Unassuming Den"
NAMES.UM_SINKMOUND_ROCK_GEMLESS = "Unassuming Den"
NAMES.GLACIALHOUND_ICESPIKE = "Ice Spike"

NAMES.UM_FEATHER_TOTEM = "Feather Idol"
NAMES.UM_GEMOLOGY_POUCH = "Gemology Pouch"
NAMES.UM_MAGNIFIER = "Ancient Gem Magnifier"
NAMES.UM_MAGNIFIER_PURPLEGEM = "Gem Magnifier"
NAMES.UM_MAGNIFIER_OBSIDIAN = "Gem Magmafier"
NAMES.UM_REEDS_LUNAR = "Maned Reeds"
NAMES.UM_STRANGE_RABBIT_ROCK = "Strange Rock"
NAMES.UM_GUANO_RAIN_PARTICLE = "Extra Fresh Guano"
NAMES.UM_HAT_NETTLEMASK = "Nettle Mask"

NAMES.UM_TENTACLE_MOON = "Gros Tentacle"
NAMES.UM_THULECITE_RAZOR = "Thulecite Razor"
NAMES.UM_TENTACLESPIKE_MOON = "Tentacle Dart"
NAMES.UM_TENTACLESPOT_MOON = "Gros Peel"
NAMES.UM_BOMB_MOON = "Transgrosgas Bomb"
NAMES.UM_BACKPACK_AMULETUSE = "Amusement Pack"
NAMES.UM_MUSHROOM_MOON = "Moon Mushroom"





