local rock1_assets =
{
    Asset("ANIM", "anim/magmarock1.zip"),
	Asset("ANIM", "anim/fyriterock.zip"),
    --Asset("MINIMAP_IMAGE", "magmarock1"),
	Asset("IMAGE", "images/map_icons/magmarock1.tex"),
	Asset("ATLAS", "images/map_icons/magmarock1.xml"),	

	
}
	
SetSharedLootTable( 'magmarock1',
{
    {'rocks',       1.00},
    {'rocks',       1.00},
    {'rocks',       1.00},
    {'goldnugget',  1.00},
    {'flint',       1.00},
    {'fossil_piece',0.2},
    {'goldnugget',  0.25},
    {'flint',       0.60},
    {'redgem',      0.1},
})

SetSharedLootTable( 'fyriterock',
{
    {'rocks',       1.00},
    {'rocks',       1.00},
    {'rocks',       1.00},
    {'um_fyrite',  1.00},
    {'flint',       1.00},
    {'fossil_piece',0.2},
    {'um_fyrite',  0.25},
    {'flint',       0.60},
    {'redgem',      0.1},
})
	
local function DamageSurroundings(inst)
	local x,y,z = inst.Transform:GetWorldPosition()
	local ents = TheSim:FindEntities(x, y, z, 2, nil,
		{ "FX", "NOCLICK", "INLIMBO", "invisible", "notarget", "noattack", "playerghost" })
	if #ents > 0 then
		for i, v in pairs(ents) do
			if v.components.burnable ~= nil then
				v.components.burnable:Ignite()
			end
			if v.components.combat then
				v.components.combat:GetAttacked(inst,50)
			end
		end
	end
end
	
local function OnWork(inst, worker, workleft)
	if inst.prefab == "fyriterock" then
		local fx = SpawnPrefab("explosivehit")
		fx.Transform:SetPosition(inst.Transform:GetWorldPosition())
		fx.Transform:SetScale(1.25,1.25,1.25)
		fx:DoTaskInTime(2,function(fx) fx:Remove() end)
		DamageSurroundings(inst)
	end
	
    if workleft <= 0 then
        local pt = inst:GetPosition()
        SpawnPrefab("rock_break_fx").Transform:SetPosition(pt.x, pt.y, pt.z)
        inst.components.lootdropper:DropLoot(pt)

        if inst.showCloudFXwhenRemoved then
            local fx = SpawnPrefab("collapse_small")
            fx.Transform:SetPosition(pt.x, pt.y, pt.z)
        end
		if not inst.doNotRemoveOnWorkDone then
	        inst:Remove()
		end
    else
        inst.AnimState:PlayAnimation(
            (workleft < TUNING.ROCKS_MINE / 3 and "low") or
            (workleft < TUNING.ROCKS_MINE * 2 / 3 and "med") or
            "full"
        )
    end
end

local function onsave(inst, data)
    data.treeSize = inst.treeSize
end

local function onload(inst, data)
    if data ~= nil and data.treeSize ~= nil then
        inst.treeSize = data.treeSize
        --V2C: Note that this will reset workleft as well
        --     Gotta change this if you set workable to savestate
        setPetrifiedTreeSize(inst)
    end
end

local function baserock_fn(bank, build, anim, minimapicon, tag, multcolour)
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddAnimState()
    inst.entity:AddSoundEmitter()
    inst.entity:AddMiniMapEntity()
    inst.entity:AddNetwork()

    MakeObstaclePhysics(inst, 1)

    if minimapicon then
        inst.MiniMapEntity:SetIcon(minimapicon)
    end

    inst.AnimState:SetBank(bank)
    inst.AnimState:SetBuild(build)

    if type(anim) == "table" then
        for i, v in ipairs(anim) do
            if i == 1 then
                inst.AnimState:PlayAnimation(v)
                inst.scrapbook_anim = v
            else
                inst.AnimState:PushAnimation(v, false)
            end
        end
    else
        inst.AnimState:PlayAnimation(anim)
        inst.scrapbook_anim = anim
    end

    MakeSnowCoveredPristine(inst)

    inst:AddTag("boulder")
    if tag then
        inst:AddTag(tag)
    end

    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end

    -- NOTE(DiogoW): Only use dependencies generated by lootdroper.
    inst.scrapbook_deps = {}

    inst:AddComponent("lootdropper")

    local workable = inst:AddComponent("workable")
    workable:SetWorkAction(ACTIONS.MINE)
    workable:SetWorkLeft(TUNING.ROCKS_MINE)
    workable:SetOnWorkCallback(OnWork)


	local colour = math.random(75,100)*0.01
	inst.AnimState:SetMultColour(colour, colour, colour, 1)


    inst:AddComponent("inspectable")
    inst.components.inspectable.nameoverride = "ROCK"

    MakeSnowCovered(inst)

    MakeHauntableWork(inst)

    return inst
end

local function rock1_fn()
    local inst = baserock_fn("magmarock1", "magmarock1", "full", "magmarock1.tex")

    if not TheWorld.ismastersim then
        return inst
    end

    inst.components.lootdropper:SetChanceLootTable('magmarock1')

    return inst
end

local function rock2_fn()
    local inst = baserock_fn("fyriterock", "fyriterock", "full", "magmarock1.tex")

    if not TheWorld.ismastersim then
        return inst
    end

    inst.components.lootdropper:SetChanceLootTable('fyriterock')

    return inst
end

return Prefab("magmarock1", rock1_fn, rock1_assets),
Prefab("fyriterock", rock2_fn, rock1_assets)