local assets =
{
    Asset("ANIM", "anim/um_guano_rock.zip"),
	Asset("IMAGE", "images/map_icons/um_guano_rock_icon.tex"),
	Asset("ATLAS", "images/map_icons/um_guano_rock_icon.xml"),		
}


local function OnWork(inst, worker, workleft)
    if workleft <= 0 then
        local pt = inst:GetPosition()
        SpawnPrefab("rock_break_fx").Transform:SetPosition(pt.x, pt.y, pt.z)
        inst.components.lootdropper:DropLoot(pt)

		inst:Remove()
    else
		if inst.tier == 3 then
			inst.AnimState:PlayAnimation(
				(workleft < TUNING.ROCKS_MINE / 3 and "tier3_low") or
				(workleft < TUNING.ROCKS_MINE * 2 / 3 and "tier3_med") or
				"tier3_full"
			)
		elseif inst.tier == 2 then
			inst.AnimState:PlayAnimation(
				(workleft < TUNING.ROCKS_MINE * 2 / 3 and "tier2_low") or
				"tier2_full"
			)
		else
			inst.AnimState:PlayAnimation("tier1")		
		end
    end
end

local function onsave(inst, data)
    data.tier = inst.tier
end

local function onload(inst, data)
    if data ~= nil and data.tier ~= nil then
        inst.tier = data.tier
        --V2C: Note that this will reset workleft as well
        --     Gotta change this if you set workable to savestate
        inst.SetTier(inst)
    end
end


local function RandomDetermineTier(inst)
	if not inst.tier then
		inst.tier = math.random(1,3)
		inst.SetTier(inst)
	end
end

SetSharedLootTable( 'um_guano_rock3',
{
    {'rocks',   1.0},
    {'rocks',   1.0},
    {'guano',   1.0},
    {'guano',   1.0},
    {'rocks',   1.0},
    {'guano',   1.0},
	{'nitre',   1.0},
	{'nitre',   1.0},
	{'um_gemology_geode_guano',  1.0},
	{'um_gemology_geode_guano',  0.1},
})

SetSharedLootTable( 'um_guano_rock2',
{
    {'rocks',   1.0},
    {'rocks',   1.0},
    {'guano',   1.0},
    {'guano',   1.0},
	{'nitre',   1.0},
	{'um_gemology_geode_guano',  0.5},
})

SetSharedLootTable( 'um_guano_rock1',
{
    {'rocks',   1.0},
    {'guano',   1.0},
	{'nitre',   0.5},
	{'um_gemology_geode_guano',  0.1},
})


local function SetTier(inst)
	if inst.tier == 3 then
		inst.components.workable:SetWorkLeft(TUNING.ROCKS_MINE)
		inst.AnimState:PlayAnimation("tier3_full")
	elseif inst.tier == 2 then
		inst.components.workable:SetWorkLeft(TUNING.ROCKS_MINE*2/3)
		inst.AnimState:PlayAnimation("tier2_full")
	else
		inst.components.workable:SetWorkLeft(TUNING.ROCKS_MINE/3)
		inst.AnimState:PlayAnimation("tier1")
	end
	inst.components.lootdropper:SetChanceLootTable('um_guano_rock'..inst.tier)
end

local function guanorock()
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddAnimState()
    inst.entity:AddSoundEmitter()
    inst.entity:AddMiniMapEntity()
    inst.entity:AddNetwork()

    MakeObstaclePhysics(inst, 1)

	inst.MiniMapEntity:SetIcon("um_guano_rock_icon.tex")

    inst.AnimState:SetBank("um_guano_rock")
    inst.AnimState:SetBuild("um_guano_rock")
	inst.AnimState:PlayAnimation("tier3_full")


    inst:AddTag("boulder")


    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end

    -- NOTE(DiogoW): Only use dependencies generated by lootdroper.
    inst.scrapbook_deps = {}

    inst:AddComponent("lootdropper")

    local workable = inst:AddComponent("workable")
    workable:SetWorkAction(ACTIONS.MINE)
    workable:SetWorkLeft(TUNING.ROCKS_MINE)
    workable:SetOnWorkCallback(OnWork)


    local colour = math.random(75,100)*0.01
    inst.AnimState:SetMultColour(colour, colour, colour, 1)


    inst:AddComponent("inspectable")
	
	inst.OnSave = onsave
	inst.OnLoad = onload
	inst.SetTier = SetTier
	inst:DoTaskInTime(0,RandomDetermineTier)
    MakeHauntableWork(inst)

	inst.Transform:SetScale(1.25,1.25,1.25)

    return inst
end

return Prefab("um_guano_rock", guanorock, assets)