local assets =
{
    Asset("ANIM", "anim/um_magmastone.zip"),
    Asset("IMAGE", "images/map_icons/um_magmastone.tex"),
    Asset("ATLAS", "images/map_icons/um_magmastone.xml"),
}

SetSharedLootTable('um_magmastone',
    {
        { 'rocks',      1.00 },
        { 'rocks',      1.00 },
        { 'nitre',      1.00 },
        { 'flint',      1.00 },
        { "goldnugget", 0.25 },
        { 'flint',      0.60 },
        { 'um_fyrite',  0.1 }
    })

SetSharedLootTable('um_magmastone_gem',
    {
        { 'um_gemology_geode_magma', 1.00 },
        { 'rocks',                   1.00 },
        { 'rocks',                   1.00 },
        { 'nitre',                   1.00 },
        { 'flint',                   1.00 },
        { "goldnugget",              0.25 },
        { 'flint',                   0.60 },
        { 'um_fyrite',               0.1 }
    })

SetSharedLootTable('um_magmastone_outcrop',
    {
        { 'um_fyrite',  1.00 },
        { 'rocks',      1.00 },
        { 'goldnugget', 1.00 },
        { 'nitre',      1.00 },
        { 'flint',      1.00 },
        { 'nitre',      0.25 },
        { 'redgem',     0.5 },
        { 'flint',      0.60 },
    })

local ROCK_STATES = {
    "gemified",
    "gemless",
    "gemlessfire"
}

local function GetState(inst)
    return inst.state
end
local function GetWorkedStateAnim(inst, workleft)
    return (workleft < TUNING.ROCKS_MINE / 3 and "low") or
        (workleft < TUNING.ROCKS_MINE * 2 / 3 and "med") or
        "full"
end


local function OnTimerDone(inst, data)
    if data ~= nil and data.name == "grow" then
        inst:SetState("gemified")
    end
end

local function SetState(inst, state)
    local prev_state = inst.state
    inst.state = state

    if type(state) == "number" then
        state = ROCK_STATES[state]
    end

    if prev_state ~= state then
        local workleft = inst.components.workable.workleft

        inst.AnimState:PlayAnimation(state .. "_" .. GetWorkedStateAnim(inst, workleft))

        if state ~= "gemless" then
            local fx = SpawnPrefab("firesplash_fx")
            fx.Transform:SetPosition(inst.Transform:GetWorldPosition())
        end

        if state == "gemlessfire" then
            inst:AddComponent("timer")
            inst:ListenForEvent("timerdone", OnTimerDone)
            inst.components.timer:StartTimer("grow", TUNING.TOTAL_DAY_TIME)
        else
            inst:RemoveComponent("timer")
        end

        if state == "gemified" then
            inst.components.lootdropper:SetChanceLootTable('um_magmastone_gem')
        else
            inst.components.lootdropper:SetChanceLootTable('um_magmastone')
        end
    end
end

local function UpdateState(inst)
    local node = TheWorld.Map:FindNodeAtPoint(inst.Transform:GetWorldPosition())
    if node ~= nil and table.contains(node.tags, "UM_ActiveLavaZone") then
        SetState(inst, "gemlessfire")
    end
end

local function OnWork(inst, worker, workleft)
    if workleft <= 0 then
        local pt = inst:GetPosition()
        SpawnPrefab("rock_break_fx").Transform:SetPosition(pt.x, pt.y, pt.z)
        inst.components.lootdropper:DropLoot(pt)

        local fx = SpawnPrefab("collapse_small")
        fx.Transform:SetPosition(pt.x, pt.y, pt.z)

        if inst:GetState() == "gemified" or inst:GetState() == "gemlessfire" then
            local outcrop = SpawnPrefab("um_magmastone_outcrop")
            outcrop.Transform:SetPosition(pt.x, pt.y, pt.z)
        end

        inst:Remove()
    else
        local anim = GetWorkedStateAnim(inst, workleft)

        inst.AnimState:PlayAnimation(inst:GetState() .. "_" .. anim)
    end
end

local function OnWorkOutcrop(inst, worker, workleft)
    if workleft <= 0 then
        local pt = inst:GetPosition()
        SpawnPrefab("rock_break_fx").Transform:SetPosition(pt.x, pt.y, pt.z)
        inst.components.lootdropper:DropLoot(pt)

        local fx = SpawnPrefab("collapse_small")
        fx.Transform:SetPosition(pt.x, pt.y, pt.z)
        inst:Remove()
    end
end


local function baserock_fn()
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddAnimState()
    inst.entity:AddSoundEmitter()
    inst.entity:AddMiniMapEntity()
    inst.entity:AddNetwork()

    MakeObstaclePhysics(inst, 1)

    inst.MiniMapEntity:SetIcon("um_magmastone.tex")

    inst.AnimState:SetBank("um_magmastone")
    inst.AnimState:SetBuild("um_magmastone")
    inst.AnimState:PlayAnimation("gemless_full")

    inst:AddTag("boulder")
    inst:AddTag("magmastone")
    inst.state = "gemless"

    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end

    inst.GetState = GetState
    inst.SetState = SetState

    -- NOTE(DiogoW): Only use dependencies generated by lootdroper.
    inst.scrapbook_deps = {}

    inst:AddComponent("lootdropper")
    inst.components.lootdropper:SetChanceLootTable('um_magmastone')

    local workable = inst:AddComponent("workable")
    workable:SetWorkAction(ACTIONS.MINE)
    workable:SetWorkLeft(TUNING.ROCKS_MINE)
    workable:SetOnWorkCallback(OnWork)

    local multcolour = 0.5
    if 0 <= multcolour and multcolour < 1 then
        local colour = multcolour + math.random() * (1.0 - multcolour)
        inst.AnimState:SetMultColour(colour, colour, colour, 1)
    end

    inst:AddComponent("inspectable")
    inst:DoTaskInTime(0, UpdateState)

    inst:DoTaskInTime(0.01, function(inst)
        if inst:GetState() ~= "gemless" then
            if TheWorld.magma_outcrops == nil then
                TheWorld.magma_outcrops = {}
            end
            TheWorld.magma_outcrops[inst.GUID] = inst
        end
    end)

    inst:ListenForEvent("onremove", function(inst)
        if inst:GetState() ~= "gemless" then
            if TheWorld.magma_outcrops ~= nil then
                TheWorld.magma_outcrops[inst.GUID] = nil
            end
        end
    end)

    MakeHauntableWork(inst)

    return inst
end

local function StartGrowingOutcrop(inst)
    print("started actually growing")
    inst.components.timer:StartTimer("grow", TUNING.TOTAL_DAY_TIME * 4)
    inst.fire_ring = SpawnPrefab("deer_fire_circle")
    --we don't make the ring a child of inst because it needs to be removed a little after inst is.
    inst.fire_ring.Transform:SetPosition(inst.Transform:GetWorldPosition())
end

local function outcrop()
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddAnimState()
    inst.entity:AddSoundEmitter()
    inst.entity:AddMiniMapEntity()
    inst.entity:AddNetwork()

    MakeObstaclePhysics(inst, 1)

    inst.MiniMapEntity:SetIcon("um_magmastone_outcrop.tex")

    inst.AnimState:SetBank("um_magmastone")
    inst.AnimState:SetBuild("um_magmastone")
    inst.AnimState:PlayAnimation("outcrop_idle")

    inst:AddTag("boulder")
    inst:AddTag("magmastone_outcrop")

    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end

    -- NOTE(DiogoW): Only use dependencies generated by lootdroper.
    inst.scrapbook_deps = {}

    inst:AddComponent("lootdropper")
    inst.components.lootdropper:SetChanceLootTable('um_magmastone_outcrop')

    local workable = inst:AddComponent("workable")
    workable:SetWorkAction(ACTIONS.MINE)
    workable:SetWorkLeft(TUNING.ROCKS_MINE)
    workable:SetOnWorkCallback(OnWorkOutcrop)

    local multcolour = 0.5
    if 0 <= multcolour and multcolour < 1 then
        local colour = multcolour + math.random() * (1.0 - multcolour)
        inst.AnimState:SetMultColour(colour, colour, colour, 1)
    end

    inst:AddComponent("inspectable")

    MakeHauntableWork(inst)

    inst.StartGrowing = StartGrowingOutcrop

    inst:AddComponent("timer")
    inst:ListenForEvent("timerdone", function(inst, data)
        if data.name == "grow" then
            inst:Remove()
            local rock = SpawnPrefab("um_magmastone")
            rock.Transform:SetPosition(inst.Transform:GetWorldPosition())
            local fx = SpawnPrefab("firesplash_fx")
            fx.Transform:SetPosition(inst.Transform:GetWorldPosition())

            if inst.fire_ring ~= nil then
                inst.fire_ring:KillFX()
            end
        end
    end)

    inst:DoTaskInTime(0, function(inst)
        if TheWorld.magma_outcrops == nil then
            TheWorld.magma_outcrops = {}
        end
        TheWorld.magma_outcrops[inst.GUID] = inst
    end)

    inst:ListenForEvent("onremove", function(inst)
        if TheWorld.magma_outcrops ~= nil then
            TheWorld.magma_outcrops[inst.GUID] = nil
        end
    end)

    return inst
end

return Prefab("um_magmastone", baserock_fn, assets),
    Prefab("um_magmastone_outcrop", outcrop, assets)
