local assets =
{
    Asset("ANIM", "anim/um_redmushtree.zip"),
	Asset("ANIM", "anim/um_bluemushtree.zip"),
	Asset("ANIM", "anim/um_greenmushtree.zip"),
	
	Asset("IMAGE", "images/map_icons/um_redmushtree_mapicon.tex"),
	Asset("ATLAS", "images/map_icons/um_redmushtree_mapicon.xml"),		

	Asset("IMAGE", "images/map_icons/um_greenmushtree_mapicon.tex"),
	Asset("ATLAS", "images/map_icons/um_greenmushtree_mapicon.xml"),	

	Asset("IMAGE", "images/map_icons/um_bluemushtree_mapicon.tex"),
	Asset("ATLAS", "images/map_icons/um_bluemushtree_mapicon.xml"),		
}


local function OnWork(inst, worker, workleft)
    if workleft <= 0 then
        local pt = inst:GetPosition()
        SpawnPrefab("rock_break_fx").Transform:SetPosition(pt.x, pt.y, pt.z)
        inst.components.lootdropper:DropLoot(pt)

        if inst.showCloudFXwhenRemoved then
            local fx = SpawnPrefab("collapse_small")
            fx.Transform:SetPosition(pt.x, pt.y, pt.z)
        end

        if not inst.doNotRemoveOnWorkDone then
            inst:Remove()
        end
    else
        inst.AnimState:PlayAnimation(
            (workleft < TUNING.ROCKS_MINE / 3 and inst.animname.."_small") or
            (workleft < TUNING.ROCKS_MINE * 2 / 3 and inst.animname.."_med") or
            inst.animname.."_tall"
        )
    end
end

local function onsave(inst, data)
	data.transformSize = inst.transformSize
end

local function onload(inst, data)
    if data then
		inst.transformSize = data.transformSize
    end
end


local function DetermineSize(inst)
	local scale
	if inst.transformSize then
		scale = inst.transformSize
	else
		if inst.prefab == "um_redmushtree_gem" or inst.prefab == "um_redmushtree_gemless" then
			scale = math.random(1.1,1.4)
		end
		if inst.prefab == "um_greenmushtree_gemless" or inst.prefab == "um_greenmushtree_gem" then
			scale = math.random(0.9,1.1)
		end
		if inst.prefab == "um_bluemushtree_gemless" or inst.prefab == "um_bluemushtree_gem" then
			scale = math.random(0.9,1.2)
		end
		inst.scale = scale
	end
	inst.Transform:SetScale(scale,scale,scale)
end


local function baserock_fn(bank, build, anim, minimapicon, tag, multcolour,color)
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddAnimState()
    inst.entity:AddSoundEmitter()
    inst.entity:AddMiniMapEntity()
    inst.entity:AddNetwork()

    MakeObstaclePhysics(inst, 1)

    if minimapicon then
        inst.MiniMapEntity:SetIcon(minimapicon)
    end

    inst.AnimState:SetBank(bank)
    inst.AnimState:SetBuild(build)

    if type(anim) == "table" then
        for i, v in ipairs(anim) do
            if i == 1 then
                inst.AnimState:PlayAnimation(v)
                inst.scrapbook_anim = v
            else
                inst.AnimState:PushAnimation(v, false)
            end
        end
    else
        inst.AnimState:PlayAnimation(anim)
        inst.scrapbook_anim = anim
    end

    MakeSnowCoveredPristine(inst)

    inst:AddTag("boulder")
    if tag then
        inst:AddTag(tag)
    end

    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end

    -- NOTE(DiogoW): Only use dependencies generated by lootdroper.
    inst.scrapbook_deps = {}

    inst:AddComponent("lootdropper")

    local workable = inst:AddComponent("workable")
    workable:SetWorkAction(ACTIONS.MINE)
    workable:SetWorkLeft(TUNING.ROCKS_MINE)
    workable:SetOnWorkCallback(OnWork)


    local colour = math.random(75,100)*0.01
    inst.AnimState:SetMultColour(colour, colour, colour, 1)


    inst:AddComponent("inspectable")
    inst.components.inspectable.nameoverride = "UM_PETRIFIED_MUSHTREE"

    MakeSnowCovered(inst)

    MakeHauntableWork(inst)

	inst.OnSave = onsave
	inst.OnLoad = onload
	inst:DoTaskInTime(0,DetermineSize)
    return inst
end

SetSharedLootTable( 'um_petmushtree',
{
    {'rocks',   1.0},
    {'rocks',   1.0},
    {'rocks',   1.0},
    {'flint',   1.0},
	{'nitre',   1.0},
	{'log',   0.6},
})

local function redgemless()
    local inst = baserock_fn("um_redmushtree_gemless", "um_redmushtree", "empty_tall", "um_redmushtree_mapicon.tex")

    if not TheWorld.ismastersim then
        return inst
    end
	inst.animname = "empty"
	
    inst.components.lootdropper:SetChanceLootTable('um_petmushtree')
 	inst.components.lootdropper:AddChanceLoot("red_cap", 1)
	inst.components.lootdropper:AddChanceLoot("red_cap", 0.1)   
	
    return inst
end

local function redgem()
    local inst = baserock_fn("um_redmushtree_gem", "um_redmushtree", "gem_tall", "um_redmushtree_mapicon.tex")

    if not TheWorld.ismastersim then
        return inst
    end
	inst.animname = "gem"
    inst.components.lootdropper:SetChanceLootTable('um_petmushtree')
	inst.components.lootdropper:AddChanceLoot("um_gemology_geode_red", 1)
	inst.components.lootdropper:AddChanceLoot("um_gemology_geode_red", 0.1)
    return inst
end

local function greengemless()
    local inst = baserock_fn("um_greenmushtree_gemless", "um_greenmushtree", "empty_tall", "um_greenmushtree_mapicon.tex")

    if not TheWorld.ismastersim then
        return inst
    end
	inst.animname = "empty"
	
    inst.components.lootdropper:SetChanceLootTable('um_petmushtree')
 	inst.components.lootdropper:AddChanceLoot("green_cap", 1)
	inst.components.lootdropper:AddChanceLoot("green_cap", 0.1)   

    return inst
end

local function greengem()
    local inst = baserock_fn("um_greenmushtree_gem", "um_greenmushtree", "gem_tall", "um_greenmushtree_mapicon.tex")

    if not TheWorld.ismastersim then
        return inst
    end
	inst.animname = "gem"
    inst.components.lootdropper:SetChanceLootTable('um_petmushtree')
	inst.components.lootdropper:AddChanceLoot("um_gemology_geode_green", 1)
	inst.components.lootdropper:AddChanceLoot("um_gemology_geode_green", 0.1)
    return inst
end

local function bluegemless()
    local inst = baserock_fn("um_bluemushtree_gemless", "um_bluemushtree", "empty_tall", "um_bluemushtree_mapicon.tex")

    if not TheWorld.ismastersim then
        return inst
    end
	inst.animname = "empty"
	
    inst.components.lootdropper:SetChanceLootTable('um_petmushtree')
 	inst.components.lootdropper:AddChanceLoot("blue_cap", 1)
	inst.components.lootdropper:AddChanceLoot("blue_cap", 0.1)   

    return inst
end

local function bluegem()
    local inst = baserock_fn("um_bluemushtree_gem", "um_bluemushtree", "gem_tall", "um_bluemushtree_mapicon.tex")

    if not TheWorld.ismastersim then
        return inst
    end
	inst.animname = "gem"
    inst.components.lootdropper:SetChanceLootTable('um_petmushtree')
	inst.components.lootdropper:AddChanceLoot("um_gemology_geode_blue", 1)
	inst.components.lootdropper:AddChanceLoot("um_gemology_geode_blue", 0.1)
    return inst
end



return Prefab("um_redmushtree_gemless", redgemless, assets),
    Prefab("um_redmushtree_gem",redgem,assets),
	Prefab("um_greenmushtree_gemless", greengemless,assets),
    Prefab("um_greenmushtree_gem",greengem,assets),
	Prefab("um_bluemushtree_gemless", bluegemless,assets),
    Prefab("um_bluemushtree_gem",bluegem,assets)