local assets =
{
    Asset("ANIM", "anim/um_rocklobster_rock.zip"),
	Asset("IMAGE", "images/map_icons/um_lobster_rock_icon.tex"),
	Asset("ATLAS", "images/map_icons/um_lobster_rock_icon.xml"),		
}

local function PissOffLobsters(inst,worker)
	local x,y,z = inst.Transform:GetWorldPosition()
	local lobsters = TheSim:FindEntities(x,y,z,24,{"rocky"})
	for i,ent in ipairs(lobsters) do
		if ent.components.health and not ent.components.health:IsDead() and ent.components.combat then
			ent.components.combat:SetTarget(worker)
		end
	end

end

local function OnWork(inst, worker, workleft)
    if workleft <= 0 then
        local pt = inst:GetPosition()
        SpawnPrefab("rock_break_fx").Transform:SetPosition(pt.x, pt.y, pt.z)
        inst.components.lootdropper:DropLoot(pt)

		inst:Remove()
    else
		inst.AnimState:PlayAnimation(
						(workleft < TUNING.ROCKS_MINE / 3 and "low") or
						(workleft < TUNING.ROCKS_MINE * 2 / 3 and "med") or
						"full"
					)
    end
	PissOffLobsters(inst,worker)
end


SetSharedLootTable( 'um_rocklobster_rock',
{
    {'rocks',   1.0},
    {'rocks',   1.0},
    {'rocks',   1.0},
	{'flint',   1.0},
	{'goldnugget',   1.0},
	{'um_gemology_geode_lobster',  1.0},
	{'um_gemology_geode_lobster',  0.1},
})


local function rockyrock()
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddAnimState()
    inst.entity:AddSoundEmitter()
    inst.entity:AddMiniMapEntity()
    inst.entity:AddNetwork()

    MakeObstaclePhysics(inst, 1)

	inst.MiniMapEntity:SetIcon("um_lobster_rock_icon.tex")

    inst.AnimState:SetBank("um_rocklobster_rock")
    inst.AnimState:SetBuild("um_rocklobster_rock")
	inst.AnimState:PlayAnimation("full")


    inst:AddTag("boulder")


    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end

    -- NOTE(DiogoW): Only use dependencies generated by lootdroper.
    inst.scrapbook_deps = {}

    inst:AddComponent("lootdropper")

    local workable = inst:AddComponent("workable")
    workable:SetWorkAction(ACTIONS.MINE)
    workable:SetWorkLeft(TUNING.ROCKS_MINE)
    workable:SetOnWorkCallback(OnWork)

	inst.components.lootdropper:SetChanceLootTable('um_rocklobster_rock')


    inst:AddComponent("inspectable")
	
	
    MakeHauntableWork(inst)

    return inst
end

return Prefab("um_rocklobster_rock", rockyrock, assets)