local assets =
{
    Asset("ANIM", "anim/um_slimestone_rock.zip"),
	Asset("IMAGE", "images/map_icons/um_slimestone_rock_icon.tex"),
	Asset("ATLAS", "images/map_icons/um_slimestone_rock_icon.xml"),		
}

local function AngerMonkeys(inst,worker)
	local x,y,z = inst.Transform:GetWorldPosition()
	local monkeys = TheSim:FindEntities(x,y,z,30,{"monkey"})
	if monkeys then
		for i,v in ipairs(monkeys) do
			if v.components.combat then
				v.components.combat:SuggestTarget(worker)
			end
		end
	end
end

local function OnWork(inst, worker, workleft)
	if inst.prefab == "um_slimestone_rock" then
		AngerMonkeys(inst,worker)
	end
    if workleft <= 0 then
        local pt = inst:GetPosition()
        SpawnPrefab("rock_break_fx").Transform:SetPosition(pt.x, pt.y, pt.z)
		inst.SoundEmitter:PlaySound("dontstarve/frog/splat")
        inst.components.lootdropper:DropLoot(pt)
		if inst.prefab == "um_slimestone_rock" then
			inst.components.lootdropper:SpawnLootPrefab("um_gemology_geode_slime")
		end
		inst:Remove()
    else
		inst.AnimState:PlayAnimation(
			(workleft < TUNING.ROCKS_MINE / 3 and "low") or
			(workleft < TUNING.ROCKS_MINE * 2 / 3 and "med") or
			"full"
		)
    end
end

SetSharedLootTable( 'um_slimestone_rock',
{
    {'rocks',   1.0},
	{'flint',   1},
	{'poop',   1},
	{'poop',   1},
	{'cutlichen',   1},
	{'beardhair',   0.33},
	{'lightbulb',   0.33},
	{'slurper_pelt',   0.33},
	{'pondeel',   0.1},	
})

local DAMAGE_ONEOF_TAGS = {"NPC_workable", "CHOP_workable", "HAMMER_workable", "MINE_workable", "DIG_workable" }

local function BreakStuff(inst)
	local x,y,z = inst.Transform:GetWorldPosition()
	local structure_ents = TheSim:FindEntities(x, 0, z, 2,nil,nil,DAMAGE_ONEOF_TAGS)
	for i,v in ipairs(structure_ents) do
		if v ~= inst then
			SpawnPrefab("collapse_small").Transform:SetPosition(v.Transform:GetWorldPosition())
			v.components.workable:Destroy(inst)		
		end			
	end
end

local function FreeFall(inst)
	local x, y, z = inst.Transform:GetWorldPosition()
	local scaleFactor = Lerp(.5, 1.5, y / 35)*6
	inst.shadow.Transform:SetScale(scaleFactor, scaleFactor, scaleFactor)
	if y < 0.4 then
		inst.AnimState:PlayAnimation("bounce",false)
		inst.AnimState:PushAnimation("full")
		inst.components.workable.workleft = TUNING.ROCKS_MINE
		
		inst.FallingTask:Cancel()
		inst.FallingTask = nil
		BreakStuff(inst)
		inst.shadow:Remove()
		inst.Physics:Stop()
		ChangeToObstaclePhysics(inst)

		--AXE hit players in the head
		local ents = TheSim:FindEntities(x, 0, z, 3, {"_health",})
		for i, v in ipairs(ents) do
			if v:IsValid() then 
				if v.components.sanity then
					if v.prefab == "wormwood" then
						v.components.sanity:DoDelta(33)
					else
						v.components.sanity:DoDelta(-50)
					end
				end
				v.components.combat:GetAttacked(inst, 300) --AXE Absolutely no mercy.
			end
		end		

		inst.Transform:SetPosition(x,0,z)
		SpawnPrefab("collapse_big").Transform:SetPosition(x,0,z)
	end
	
end

local function BeginFreeFall(inst)
	inst.SoundEmitter:PlaySound("dontstarve/common/meteor_spawn")
	inst.AnimState:PlayAnimation("fall")
	inst.components.workable.workleft = -1
	local x,y,z = inst.Transform:GetWorldPosition()
	MakeInventoryPhysics(inst, 1)
	inst.shadow = SpawnPrefab("warningshadow")
	inst.shadow:ListenForEvent("onremove", function(inst) inst.shadow:Remove() end, inst)
	inst.shadow.Transform:SetPosition(x, 0, z)	
	inst.FallingTask = inst:DoPeriodicTask(FRAMES,FreeFall)
	inst.shadow.AnimState:SetDeltaTimeMultiplier(0.25)
	inst.Transform:SetPosition(x,y+30,z)
end

local function mainrocks(bank)
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddAnimState()
    inst.entity:AddSoundEmitter()
    inst.entity:AddMiniMapEntity()
    inst.entity:AddNetwork()

    MakeObstaclePhysics(inst, 1.5)

	inst.MiniMapEntity:SetIcon("um_slimestone_rock_icon.tex")

    inst.AnimState:SetBank(bank)
    inst.AnimState:SetBuild("um_slimestone_rock")
	inst.AnimState:PlayAnimation("full")


    inst:AddTag("boulder")

    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end

    -- NOTE(DiogoW): Only use dependencies generated by lootdroper.
    inst.scrapbook_deps = {}

    inst:AddComponent("lootdropper")


    inst:AddComponent("workable")
    inst.components.workable:SetWorkAction(ACTIONS.MINE)
    inst.components.workable:SetWorkLeft(TUNING.ROCKS_MINE)
    inst.components.workable:SetOnWorkCallback(OnWork)
	inst.components.lootdropper:SetChanceLootTable('um_slimestone_rock')
	
    local colour = math.random(75,100)*0.01
    inst.AnimState:SetMultColour(colour, colour, colour, 1)


    inst:AddComponent("inspectable")
	
    MakeHauntableWork(inst)

	inst.Transform:SetScale(1.25,1.25,1.25)
	
	inst.BeginFreeFall = BeginFreeFall

    return inst
end

local function slime_gemless()
	local inst = mainrocks("um_slimestone_gemless")
	
	return inst
end

local function slime()
	local inst = mainrocks("um_slimestone_gem")
	
	return inst
end

local function IdentifyRockDensity(inst)
	local x,y,z = inst.Transform:GetWorldPosition()
	local rocks = TheSim:FindEntities(x,y,z,64,{"boulder"})

	local gemless = {}
	local gem = {}
	for i,rock in ipairs(rocks) do
		if rock.prefab == "um_slimestone_rock" then
			table.insert(gem,rock)
		end
		if rock.prefab == "um_slimestone_rock_gemless" then
			table.insert(gemless,rock)
		end
	end
	return gemless, gem
end

local function RangeDetect(pt,ent)
	if ent:GetDistanceSqToPoint(pt) < 16 then
		return true
	else
		return false
	end
end

local function TooCloseOtherRocks(pt, gemless, gem)
	local range_detect_trigger = false
	for i,v in ipairs(gemless) do
		range_detect_trigger = RangeDetect(pt,v)
		if range_detect_trigger == true then
			return range_detect_trigger
		end
	end
	for i,v in ipairs(gem) do
		range_detect_trigger = RangeDetect(pt,v)
		if range_detect_trigger == true then --AXE Terminate early if it found something
			return range_detect_trigger
		end
	end
	return range_detect_trigger
end

local function RespawnRocks(inst)
	local gemless,gem = IdentifyRockDensity(inst)
	if (#gemless + #gem) > 12 then
		return
	end
	
	local offset = FindWalkableOffset(inst:GetPosition(), TWOPI*math.random(), math.random(4,32),64,function(pt) return not TooCloseOtherRocks(pt,gemless,gem) end)
	local prefabname = math.random() > 0.75 and #gem < 2 and "um_slimestone_rock" or "um_slimestone_rock_gemless"

	if prefabname == "um_slimestone_rock" then
		local monkeybarrel = FindEntity(inst,64,function(ent) return ent.prefab == "monkeybarrel" end,function(pt) return not TooCloseOtherRocks(pt,gemless,gem) end)
		if monkeybarrel then
			offset = FindWalkableOffset(monkeybarrel:GetPosition(), TWOPI*math.random(), math.random(4,5),6)
		end
	end

	local rock = SpawnPrefab(prefabname)
	local x,y,z = inst.Transform:GetWorldPosition()
	rock.Transform:SetPosition(x+offset.x,y,z+offset.z)

	if inst.entity:IsAwake() then --AXE Only trigger the falling sequence if the rock is awake
		rock.BeginFreeFall(rock)
	else
		BreakStuff(inst) -- AXE However... still break stuff nearby as if it did fall.
	end
end

local function fnnode()
    local inst = CreateEntity()

    inst.entity:AddTransform()
    inst.entity:AddNetwork()
    inst.entity:SetPristine()

    if not TheWorld.ismastersim then
        return inst
    end
	
    inst:ListenForEvent("startquake", function()
		if TheWorld.state.nightmarephase == "wild" then
			inst:DoTaskInTime(math.random(4,10),function(inst)
				RespawnRocks(inst)
			end)
		end
    end, TheWorld.net)			
	
	inst.RespawnRocks = RespawnRocks --AXE For calling during testing
    return inst
end

return Prefab("um_slimestone_rock_gemless", slime_gemless, assets),
Prefab("um_slimestone_rock", slime, assets),
Prefab("um_slimestone_respawner", fnnode)