--------------------------------------------------------------------------------------------------------------------
 
local RECIPE_BUILDER_TAG_LOOKUP = {
    alchemist = "wilson",
    balloonomancer = "wes",
    battlesinger = "wathgrithr",
    bookbuilder = "wickerbottom",
    clockmaker = "wanda",
    elixirbrewer = "wendy",
    gem_alchemistI = "wilson",
    gem_alchemistII = "wilson",
    gem_alchemistIII = "wilson",
    ghostlyfriend = "wendy",
    handyperson = "winona",
    ick_alchemistI = "wilson",
    ick_alchemistII = "wilson",
    ick_alchemistIII = "wilson",
    leifidolcrafter = "woodie",
    masterchef = "warly",
    merm_builder = "wurt",
    ore_alchemistI = "wilson",
    ore_alchemistII = "wilson",
    ore_alchemistIII = "wilson",
    pebblemaker = "walter",
    pinetreepioneer = "walter",
    plantkin = "wormwood",
    saplingcrafter = "wormwood",
    berrybushcrafter = "wormwood",
    juicyberrybushcrafter = "wormwood",
    reedscrafter = "wormwood",
    lureplantcrafter = "wormwood",
    syrupcrafter = "wormwood",
    carratcrafter = "wormwood",
    lightfliercrafter = "wormwood",
    fruitdragoncrafter = "wormwood",
    professionalchef = "warly",
    pyromaniac = "willow",
    shadowmagic = "waxwell",
    skill_wilson_allegiance_lunar = "wilson",
    skill_wilson_allegiance_shadow = "wilson",
    spiderwhisperer = "webber",
    strongman = "wolfgang",
    upgrademoduleowner = "wx78",
    valkyrie = "wathgrithr",
    werehuman = "woodie",
    wolfgang_coach = "wolfgang",
    wolfgang_dumbbell_crafting = "wolfgang",
    woodcarver1 = "woodie",
    woodcarver2 = "woodie",
    woodcarver3 = "woodie",
}

-- key: string
-- value: string, number, boolean or string array (does not work for map-type tables or arrays of non-strings).
local function Scrapbook_AddInfo(tbl, key, value)
    if value == nil then return end

    assert(checkstring(key), string.format("Parameter [key] must be of type string, and it's [%s].", type(key)))

    if type(value) == "table" then
        value = string.format('{"%s"}', table.concat(value, '", "'))
    end

    local add_quotes = checkstring(value) and value:sub(1, 1) ~= "{"

    table.insert(tbl, string.format('%s=%s', key, add_quotes and '"' .. value .. '"' or tostring(value)))
end

local function Scrapbook_WriteToFile(buffer)
    local str = "\n-- AUTOGENERATED FROM d_createscrapbookdata()   < debugcommands.lua >\n\nreturn {\n%s\n}\n"
    local entries = {}

    for i, prefab, data in sorted_pairs(buffer) do
        table.insert(entries, string.format('    %s = {%s},', prefab, table.concat(data, ", ")))
    end

    local f = io.open(TUNING.DSTU.MODROOT .. "scripts/screens/redux/scrapbookdata_changes.lua", "w")

    if f ~= nil then
        f:write(string.format(str, table.concat(entries, "\n")))
    end
end

local function Scrapbook_IsOnCraftingFilter(filter, entry)
    return table.contains(CRAFTING_FILTERS[string.upper(filter)].recipes, entry)
end

local function Scrapbook_DefineSubCategory(t)
    local subcat = nil

    local foodtype = t.components.edible ~= nil and t.components.edible.foodtype or nil

    if t:HasOneOfTags({ "wall", "wallbuilder" }) then
        subcat = "wall"
    elseif t:HasTag("haunted") then
        subcat = "hauntedtoy"
    elseif t:HasTag("singingshell") then
        subcat = "shell"
    elseif t:HasTag("bird") then
        subcat = "bird"
    elseif t:HasTag("pig") and not t:HasTag("manrabbit") then
        subcat = "pig"
    elseif t:HasTag("merm") then
        subcat = "merm"
    elseif t:HasTag("hound") then
        subcat = "hound"
    elseif t:HasTag("chess") then
        subcat = "clockwork"
    elseif t:HasTag("oceanfish") then
        subcat = "oceanfish"
    elseif t:HasTag("wagstafftool") then
        subcat = "wagstafftool"
    elseif t:HasTag("pocketwatch") then
        subcat = "pocketwatch"
    elseif t:HasTag("groundtile") then
        subcat = "turf"
    elseif t:HasTag("backpack") then
        subcat = "backpack"
    elseif t:HasTag("chest") or Scrapbook_IsOnCraftingFilter("CONTAINERS", t.prefab) then
        subcat = "container"
    elseif t:HasTag("battlesong") then
        subcat = "battlesong"
    elseif t:HasTag("ghostlyelixir") then
        subcat = "elixer"
    elseif t:HasTag("farm_plant") then
        subcat = "farmplant"
    elseif t.components.tool or t.scrapbook_subcat == "tool" then
        subcat = "tool"
    elseif t.components.weapon or t.scrapbook_subcat == "weapon" then
        subcat = "weapon"
    elseif t:HasTag("spidermutator") then
        subcat = "mutator"
    elseif foodtype ~= nil and
        foodtype ~= FOODTYPE.GENERIC and foodtype ~= FOODTYPE.GOODIES and foodtype ~= FOODTYPE.MEAT and
        foodtype ~= FOODTYPE.VEGGIE and foodtype ~= FOODTYPE.HORRIBLE and foodtype ~= FOODTYPE.INSECT and
        foodtype ~= FOODTYPE.SEEDS and foodtype ~= FOODTYPE.RAW and foodtype ~= FOODTYPE.BERRY
    then
        subcat = "element"
    elseif t.components.armor or t.prefab == "armorskeleton" then
        subcat = "armor"
    elseif t.pieceid then
        subcat = "statue"
    elseif t.components.equippable and t.components.equippable.equipslot == EQUIPSLOTS.BODY and not t:HasTag("heavy") then
        subcat = "clothing"
    elseif t:HasTag("hat") then
        subcat = "hat"
    elseif t.components.oceanfishingtackle then
        subcat = "tackle"
    elseif t.components.prototyper then
        subcat = "craftingstation"
    elseif t:HasTag("shadow") then
        subcat = "shadow"
    elseif t:HasTag("book") then
        subcat = "book"
    elseif t:HasTag("winter_ornament") then
        subcat = "ornament"
    elseif string.find(t.prefab, "trinket") then
        subcat = "trinket"
    elseif t.components.upgrademodule then
        subcat = "upgrademodule"
    elseif t:HasTag("halloween_ornament") then
        subcat = "halloweenornament"
    elseif t:HasTag("spider") then
        subcat = "spider"
    elseif t:HasTag("insect") then
        subcat = "insect"
    elseif (t:HasTag("tree") or table.contains({ "cave_banana_tree" }, t.prefab)) and not t:HasOneOfTags({ "monster", "leif" }) then
        subcat = "tree"
    elseif (t.prefab:find("atrium_")) and not table.contains({ "atrium_key" }, t.prefab) then
        subcat = "atrium"
    elseif Scrapbook_IsOnCraftingFilter("RIDING", t.prefab) then
        subcat = "riding"
    elseif Scrapbook_IsOnCraftingFilter("SEAFARING", t.prefab) or
        Scrapbook_IsOnCraftingFilter("SEAFARING", t.prefab .. "_item") or
        Scrapbook_IsOnCraftingFilter("SEAFARING", t.prefab .. "_kit")
    then
        subcat = "seafaring" -- Keep it low priority!
    elseif t:HasTag("structure") then
        subcat = "structure" -- Keep it low priority!
    end

    if subcat ~= nil and not STRINGS.SCRAPBOOK.SUBCATS[string.upper(subcat)] then
        print(string.format("[!!!!]  Sub-category [ %s ] isn't defined in STRINGS.SCRAPBOOK.SUBCATS!", subcat))
    end

    return subcat
end

local SCRAPBOOK_NAME_LOOKUP =
{
    mooseegg = "mooseegg1",
    moose = "moose1",
    ruins_chair = "relic",
    chessjunk1 = "chessjunk1",
    chessjunk2 = "chessjunk1",
    chessjunk3 = "chessjunk1",

    sketch = "sketch_scrapbook",
    tacklesketch = "tacklesketch_scrapbook",
    cookingrecipecard = "cookingrecipecard_scrapbook",
}

local function Scrapbook_DefineName(t)
    if t.scrapbook_prefab then
        return t.scrapbook_prefab
    end

    if SCRAPBOOK_NAME_LOOKUP[t.prefab] then
        return SCRAPBOOK_NAME_LOOKUP[t.prefab]
    end

    local name = t.nameoverride or t.prefab

    if t:HasTag("farm_plant") then
        name = t.prefab
    end

    if not STRINGS.NAMES[string.upper(name)] then
        print(string.format("[!!!!]  Name [ %s ] isn't defined in STRINGS.NAMES!", name))
    end

    return name
end


local function Scrapbook_DefineType(t, entry)
    local thingtype = "thing"

    local foodtype = t.components.edible ~= nil and t.components.edible.foodtype or nil

    if t.components.pointofinterest then
        thingtype = "POI"
    elseif t.scrapbook_thingtype then
        thingtype = t.scrapbook_thingtype
    elseif t:HasTag("oceanfish") then
        thingtype = "creature"
    elseif foodtype ~= nil and (
            foodtype == FOODTYPE.GENERIC or foodtype == FOODTYPE.GOODIES or foodtype == FOODTYPE.MEAT or
            foodtype == FOODTYPE.VEGGIE or foodtype == FOODTYPE.HORRIBLE or foodtype == FOODTYPE.INSECT or
            foodtype == FOODTYPE.SEEDS or foodtype == FOODTYPE.RAW or foodtype == FOODTYPE.BERRY
        ) then
        thingtype = "food"
    elseif t:HasOneOfTags({ "epic", "crabking" }) or t.prefab == "shadow_rook" or t.prefab == "shadow_bishop" or t.prefab == "shadow_knight" then
        thingtype = "giant"
    elseif entry == "balloonvest" or entry == "balloonhat" or entry == "balloonspeed" then
        thingtype = "item"
    elseif t.prefab == "pumpkin_lantern" then
        thingtype = "thing"
    elseif t.prefab == "fused_shadeling_bomb" or
        t.prefab == "smallghost" or
        t.prefab == "mushgnome" or
        t.prefab == "wobybig" or
        t.prefab == "stagehand"
    then
        thingtype = "creature"
    elseif t.components.health and
        not t:HasOneOfTags({ "structure", "farm_plant", "tree", "plant", "moonstorm_static", "wall", "boatbumper", "groundspike", "smashable", "boat" }) and
        t.prefab ~= "hedgehound_bush" and
        t.prefab ~= "eyeturret" and
        t.prefab ~= "spiderhole" and
        t.prefab ~= "slurtlehole"
    then
        thingtype = "creature"
    elseif t.components.inventoryitem and not t.components.health then
        thingtype = "item"
    end

    if not table.contains(SCRAPBOOK_CATS, thingtype) then
        print(string.format("[!!!!]  Thing type [ %s ] isn't defined in SCRAPBOOK_CATS!", thingtype))
    end

    return thingtype
end

local function Scrapbook_DefineAnimation(t)
    local anim = nil

    if t.scrapbook_anim then
        anim = t.scrapbook_anim
    elseif t:HasTag("campfire") and t.prefab ~= "cotl_tabernacle_level3" then
        anim = "scrapbook"
    elseif t.AnimState:IsCurrentAnimation("idle_dead") then
        anim = "idle_dead"
    elseif t.AnimState:IsCurrentAnimation("idle_cooked") then
        anim = "idle_cooked"
    elseif t.prefab == "shadow_forge_kit" then
        anim = "kit"
    elseif t.prefab == "lunar_forge_kit" then
        anim = "kit"
    elseif t:HasTag("tree") and not table.contains({ "livingtree", "marsh_tree", "oceantree", "driftwood_tall", "driftwood_small1", "mushtree_tall_webbed" }, t.prefab) then
        anim = "idle_tall"
    elseif t.winter_ornamentid and t:HasTag("lightbattery") then
        anim = t.winter_ornamentid .. "_on"
    elseif t.winter_ornamentid then
        anim = t.winter_ornamentid
    elseif t.prefab == "dug_bananabush" then
        anim = "idle_big"
    elseif t:HasTag("battlesong") then
        anim = t.prefab
    elseif t.prefab == "abigail_flower" then
        anim = "level3_loop"
    elseif t.AnimState:IsCurrentAnimation("f1") or
        t.AnimState:IsCurrentAnimation("f2") or
        t.AnimState:IsCurrentAnimation("f3") then
        anim = "f1"
    elseif t.AnimState:IsCurrentAnimation("rotten") then
        anim = "rotten"
    elseif t.AnimState:IsCurrentAnimation("pack_loop") then
        anim = "pack_loop"
    elseif t.AnimState:IsCurrentAnimation("idle_loop") then
        anim = "idle_loop"
    elseif t.AnimState:IsCurrentAnimation("idle_med") or t.AnimState:IsCurrentAnimation("idle_tall") or t.AnimState:IsCurrentAnimation("idle_short") then
        anim = "idle_med"
    elseif t.AnimState:IsCurrentAnimation("idle_sit") then
        anim = "idle_sit"
    elseif t.prefab == "squid" or t.prefab == "lightcrab" then
        anim = "idle"
    elseif t.AnimState:IsCurrentAnimation("idle1") or
        t.AnimState:IsCurrentAnimation("idle2") or
        t.AnimState:IsCurrentAnimation("idle3") or
        t.AnimState:IsCurrentAnimation("idle4") or
        t.AnimState:IsCurrentAnimation("idle5") or
        t.AnimState:IsCurrentAnimation("idle6") or
        t.AnimState:IsCurrentAnimation("idle7") or
        t.AnimState:IsCurrentAnimation("idle8") or
        t.AnimState:IsCurrentAnimation("idle9") or
        t.AnimState:IsCurrentAnimation("idle10") then
        anim = "idle1"
    elseif t.AnimState:IsCurrentAnimation("cooked") then
        anim = "cooked"
    elseif t.AnimState:IsCurrentAnimation("fly_loop") then
        anim = "fly_loop"
    elseif t.AnimState:IsCurrentAnimation("anim") then
        anim = "anim"
    elseif t.sg and t.sg:HasState("idle") then
        anim = "idle"
    end

    if not anim then
        local bank = nil
        -- AnimState:GetHistoryData is an unreliable function that should only
        -- be used in dev environments. DO NOT use it in the game code.
        bank, anim = t.AnimState:GetHistoryData()
    end

    return anim
end

local function Scrapbook_GetSanityAura(inst)
    local sanity = inst.components.sanityaura.aura

    if inst.components.sanityaura.aurafn then
        sanity = inst.components.sanityaura.aurafn(inst, ThePlayer)
    end

    if inst:HasTag("brightmareboss") or inst:HasTag("brightmare_guard") then
        sanity = sanity * -1
    end

    return sanity ~= 0 and sanity or nil
end

--[[
    Manual information available to insert into prefabs:

        scrapbook_adddeps: Add dependencies (string array).
        scrapbook_anim: Anim to play (string).
        scrapbook_animoffsetx: Image position X offset (number).
        scrapbook_animoffsety: Image position Y offset (number).
        scrapbook_animpercent: Animation percent (number).
        scrapbook_areadamage: Area damage (number).
        scrapbook_bank: Overrides bank (string).
        scrapbook_build: Overrides build (string).
        scrapbook_damage: Damage, for creatures (number, string or array with 2 numbers (value range)).
        scrapbook_deps: Overrides default prefab dependencies (string array).
        scrapbook_fueled_max: Overrides components.fueled.maxfuel (number).
        scrapbook_healthvalue: Health food value (number).
        scrapbook_hide: Symbols and/or Layers to hide (string array).
        scrapbook_hidehealth: Hide health data (boolean).
        scrapbook_hidesymbol: Symbols to hide (string array).
        scrapbook_hungervalue: Hunger food value (number).
        scrapbook_maxhealth: Override health data (number, string or array with 2 numbers (value range)).
        scrapbook_nodamage: Hide weapon data (damage, planar damage, range) (boolean).
        scrapbook_overridedata: String array or string arrays of symbol override (symbol, build, symbol_in_build).
        scrapbook_persishable: Overrides components.perishable.perishtime (number).
        scrapbook_planardamage: Planar damage, for creatures and weapons (number).
        scrapbook_prefab: Used by "prefab" and "name" entries (string).
        scrapbook_removedeps: Remove dependencies (string array).
        scrapbook_sanityaura: Sanity Aura (number).
        scrapbook_sanityvalue: Sanity food value (number).
        scrapbook_scale: Scale (number).
        scrapbook_specialinfo: Entry in STRINGS.SCRAPBOOK.SPECIALINFO (string).
        scrapbook_speechname: Entry in STRINGS.CHARACTERS.GENERIC.DESCRIBE (string).
        scrapbook_subcat: Sub-Category (string).
        scrapbook_tex: Icon texture (without .tex) (string).
        scrapbook_thingtype: Category (string).
        scrapbook_weapondamage: Damage, for weapons (number, string or array with 2 numbers (value range)).
        scrapbook_weaponrange: Hit range (number).
        scrapbook_workable: Overrides components.workable.action.id (string).
]]

local SKIP_SPECIALINFO_CHECK =
{
    WATERINGCAN = true,
    BUNDLEWRAP = true,
    MUSHROOMSPROUT = true,
    DUMBBELL = true,
    BUNDLE = true,
}

-- NOTES(DiogoW): There is no need to recreate this every time d_createscrapbookdata() is called.
-- Use d_printscrapbookrepairmaterialsdata() to update.
local REPAIR_MATERIAL_DATA =
{
    stone = { "cutstone", "wall_stone_item", "rocks" },
    fossil = { "fossil_piece" },
    gears = { "wagpunk_bits", "gears" },
    ice = { "ice" },
    shell = { "slurtle_shellpieces" },
    hay = { "cutgrass", "wall_hay_item" },
    moonrock = { "moonrockcrater", "wall_moonrock_item", "moonrocknugget" },
    kelp = { "kelp" },
    wood = { "boatpatch", "treegrowthsolution", "wall_wood_item", "driftwood_log", "log", "livinglog", "twigs", "boards" },
    gem = { "opalpreciousgem", "yellowgem", "redgem", "greengem", "purplegem", "orangegem", "bluegem" },
    thulecite = { "thulecite_pieces", "thulecite", "wall_ruins_item" },
    sculpture = { "sculpture_bishophead", "sculpture_rooknose", "sculpture_knighthead" },
    moon_altar = { "moon_altar_icon", "moon_altar_crown", "moon_altar_glass", "moon_altar_idol", "moon_altar_seed", "moon_altar_ward" },
    nightmare = { "nightmarefuel", "horrorfuel" },
    dreadstone = { "wall_dreadstone_item", "dreadstone" },

    voidcloth = { "voidcloth_kit" },
    wagpunk_bits = { "wagpunkbits_kit" },
    lunarplant = { "lunarplant_kit" },
}

local scrapbookprefabs = require("scrapbook_prefabs")
local um_scrapbookprefabs = require("um_scrapbook_prefabs")

function d_printscrapbookrepairmaterialsdata()
    local repair_data = {}
    local forgerepair_data = {}

    for entry, _ in pairs(scrapbookprefabs) do
        local t = SpawnPrefab(entry)

        local material = t.components.repairer ~= nil and t.components.repairer.repairmaterial or nil

        if material ~= nil then
            repair_data[material] = repair_data[material] or {}

            table.insert(repair_data[material], t.scrapbook_prefab or entry)
        end

        local forge_material = t.components.forgerepair ~= nil and t.components.forgerepair.repairmaterial or nil

        if forge_material ~= nil then
            forgerepair_data[forge_material] = forgerepair_data[forge_material] or {}

            table.insert(forgerepair_data[forge_material], t.scrapbook_prefab or entry)
        end

        t:Remove()
    end

    local str = {}

    for material, prefabs in pairs(repair_data) do
        table.insert(str, string.format('   %s = { "%s" },', material, table.concat(prefabs, '", "')))
    end
    for material, prefabs in pairs(forgerepair_data) do
        table.insert(str, string.format('   %s = { "%s" },', material, table.concat(prefabs, '", "')))
    end

    print("\n" .. table.concat(str, "\n") .. "\n")
end

local prettyline = "\n_________________________________________\n"

function d_create_diffchecker_scrapbookdata(print_missing_icons)
    if not TheWorld.state.isautumn or TheWorld.state.israining then
        -- Force the season (many entities change the build/animation during certain seasons).
        TheWorld:PushEvent("ms_setseason", "autumn")

        -- Stop rain (many entities change the build/animation during rain).
        TheWorld:PushEvent("ms_forceprecipitation", false)

        -- Push events and then rerun the command!
        scheduler:ExecuteInTime(0.05, ExecuteConsoleCommand, nil, string.format("d_createscrapbookdata(%s)", tostring(print_missing_icons or "")))
        return
    end

    print(prettyline)
    print("SCRAPBOOK DATA - WARNINGS!\n")

    local icons_missing = {}
    local specialinfo_list = {}
    local scrapbookdata = {}
    local currententry = nil

    local AddInfo = function(...) Scrapbook_AddInfo(scrapbookdata[currententry], ...) end

    local exporter_data_helper = io.open("scripts/scrapbookdata_no_package.lua", "w")
    exporter_data_helper:write("-- AUTOGENERATED FROM d_createscrapbookdata()\n")
    exporter_data_helper:write("return {\n")

    for entry, _ in pairs(scrapbookprefabs) do
        if entry ~= "archive_switch_base" then
            if um_scrapbookprefabs[entry] == nil then
                currententry = entry
                scrapbookdata[entry] = {}

                local t = SpawnPrefab(entry)

                if t == nil then
                    print(string.format("[!!!!]  Aborting data creation command! Entry [%s] is not a valid prefab!", entry))
                    return
                end

                t.Transform:SetRotation(90)

                ---------------------------------::   NAME   ::---------------------------------

                local name = Scrapbook_DefineName(t)

                ---------------------------------::   SUB-CATEGORIES   ::---------------------------------

                local subcat = Scrapbook_DefineSubCategory(t)

                ---------------------------------::   TYPE   ::---------------------------------

                local thingtype = Scrapbook_DefineType(t, entry)

                ---------------------------------::   ANIMATION   ::---------------------------------

                if t.sg and t.sg:HasState("idle") then
                    t.sg:GoToState("idle")
                end

                local anim = Scrapbook_DefineAnimation(t)

                ---------------------------------::   TEX   ::---------------------------------

                local tex = (t.scrapbook_tex or (t.components.inventoryitem ~= nil and t.components.inventoryitem.imagename) or entry) .. ".tex"

                if thingtype == "item" or thingtype == "food" then
                    if not GetInventoryItemAtlas(tex) then
                        print(string.format("[!!!!]  Atlas for texture [ %s ] not found in inventoryimagesX!", tex))
                    end
                else
                    if not GetScrapbookIconAtlas(tex) then
                        if print_missing_icons then
                            local file = t.scrapbook_build or t.AnimState:GetBuild()
                            local icon = t.scrapbook_tex or entry

                            table.insert(icons_missing, { icon = icon, file = file, anim = anim })
                        else
                            print(string.format("[!!!!]  Atlas for texture [ %s ] not found in scrapbook_iconsX!", tex))
                        end
                    end
                end

                -- NOTES(JBK): The hash is redundant data and is only here to aid the exporter for backend services.
                -- So we will save it to a file that does not get loaded for the game.
                exporter_data_helper:write(string.format("[\"%s\"] = 0x%X,\n", entry, hash(entry)))

                AddInfo("name", name)
                AddInfo("tex", tex)
                AddInfo("subcat", subcat)
                AddInfo("type", thingtype)
                AddInfo("prefab", t.scrapbook_prefab or entry)

                ---------------------------------::   SPEECHNAME   ::---------------------------------

                local speechname = t.scrapbook_speechname or t.nameoverride or (t.components.inspectable ~= nil and t.components.inspectable.nameoverride) or nil
                if speechname ~= nil and string.upper(speechname) ~= string.upper(entry) then
                    AddInfo("speechname", speechname)
                end

                if t.scrapbook_speechname ~= nil and string.lower(t.scrapbook_speechname) == string.lower(entry) then
                    print(string.format("[!!!!]  inst.scrapbook_speechname = %s is unecessary in entry [ %s ]!", t.scrapbook_speechname, entry))
                end

                if t.scrapbook_speechname ~= nil and not STRINGS.CHARACTERS.GENERIC.DESCRIBE[string.upper(t.scrapbook_speechname)] then
                    print(string.format("[!!!!]  Speech Name [ %s ] isn't defined in STRINGS.CHARACTERS.GENERIC.DESCRIBE!", t.scrapbook_speechname))
                end

                if t.scrapbook_inspectonseen == nil and
                    t.components.inspectable == nil and
                    t.components.health == nil
                then
                    print(string.format("[!!!!] [ %s ] cannot be inspected! Please add \"inst.scrapbook_inspectonseen = true\" to the prefab (common).", entry))
                end

                ---------------------------------::   SANITY   ::---------------------------------

                if t.scrapbook_sanityaura then
                    AddInfo("sanityaura", t.scrapbook_sanityaura)
                elseif t.components.sanityaura and Scrapbook_GetSanityAura(t) then
                    AddInfo("sanityaura", Scrapbook_GetSanityAura(t))
                end

                ---------------------------------::   HEALTH   ::---------------------------------

                local maxhealth = not t.scrapbook_hidehealth and (t.scrapbook_maxhealth or (t.components.health ~= nil and t.components.health.maxhealth)) or nil
                if maxhealth ~= nil then
                    if type(maxhealth) == "table" then
                        maxhealth = string.format("%d-%d", maxhealth[1], maxhealth[2])
                    end

                    AddInfo("health", maxhealth)
                end

                ---------------------------------::   DAMAGE   ::---------------------------------

                local damage = t.scrapbook_damage or (t.components.combat ~= nil and t.components.combat.defaultdamage) or nil
                if damage ~= nil then
                    if type(damage) == "table" then
                        local mod = not t.scrapbook_ignoreplayerdamagemod and t.components.combat ~= nil and t.components.combat.playerdamagepercent or 1
                        damage = string.format("%d-%d", damage[1] * mod, damage[2] * mod)
                    end

                    if checkstring(damage) or damage > 0 then
                        AddInfo("damage", (checkstring(damage) or t.scrapbook_damage) and damage or damage * (t.components.combat.playerdamagepercent or 1))
                    end
                end

                local planardamage = t.scrapbook_planardamage or (t.components.planardamage ~= nil and t.components.planardamage.basedamage) or nil
                if planardamage ~= nil and planardamage > 0 then
                    AddInfo("planardamage", planardamage)
                end

                AddInfo("areadamage", t.scrapbook_areadamage)

                ---------------------------------::   STACK   ::---------------------------------

                if t.components.stackable then
                    local stacksize = t.prefab == "wortox_soul" and TUNING.WORTOX_MAX_SOULS or t.components.stackable.maxsize

                    AddInfo("stacksize", stacksize)
                end

                ---------------------------------::   FOOD   ::---------------------------------

                if t.components.edible then
                    AddInfo("hungervalue", t.scrapbook_hungervalue or t.components.edible.hungervalue)
                    AddInfo("healthvalue", t.scrapbook_healthvalue or t.components.edible.healthvalue)
                    AddInfo("sanityvalue", t.scrapbook_sanityvalue or t.components.edible.sanityvalue)
                end

                if t.components.edible and t.components.edible.foodtype then
                    AddInfo("foodtype", t.components.edible.foodtype)

                    if not STRINGS.SCRAPBOOK.FOODTYPE[t.components.edible.foodtype] then
                        print(string.format("[!!!!]  Food Type [ %s ] isn't defined in STRINGS.SCRAPBOOK.FOODTYPE!", t.components.edible.foodtype))
                    end
                end

                ---------------------------------::   WEAPON   ::---------------------------------

                if (t.components.weapon or t.scrapbook_weapondamage) and not t.scrapbook_nodamage then
                    if t.prefab == "bomb_lunarplant" then
                        AddInfo("weapondamage", t.components.weapon.damage)
                        AddInfo("planardamage", TUNING.BOMB_LUNARPLANT_PLANAR_DAMAGE)
                        AddInfo("weaponrange", t.components.weapon.hitrange)
                    else
                        if t.scrapbook_weapondamage or (t.components.weapon and t.components.weapon.damage) then
                            local weapondamage = t.scrapbook_weapondamage

                            if type(weapondamage) == "table" then
                                weapondamage = string.format("%d-%d", weapondamage[1], weapondamage[2])
                            end

                            if not weapondamage and type(t.components.weapon.damage) == "function" then
                                print(string.format(">> Prefab [ %s ] has a function defined for components.weapon.damage!", t.prefab))
                            else
                                if not weapondamage and t.components.weapon.damage then
                                    weapondamage = t.components.weapon.damage
                                end
                                AddInfo("weapondamage", weapondamage)
                            end
                        end

                        local hitrange = t.scrapbook_weaponrange or (t.components.weapon ~= nil and t.components.weapon.hitrange) or nil
                        if hitrange ~= nil then
                            AddInfo("weaponrange", hitrange)
                        end
                    end
                end

                ---------------------------------::   ARMOR   ::---------------------------------

                if t.components.armor then
                    AddInfo("armor", t.components.armor.maxcondition)
                    AddInfo("absorb_percent", t.components.armor.absorb_percent)

                    if t.components.planardefense then
                        AddInfo("armor_planardefense", t.components.planardefense.basedefense)
                    end
                end

                ---------------------------------::   TOOL   ::---------------------------------

                if t.components.finiteuses then
                    -- FIXME(JBK): This is a bad assumption for tools that have multiple uses with different use rates but will fix up most cases.
                    local count = 0
                    for _ in pairs(t.components.finiteuses.consumption) do
                        count = count + 1
                    end
                    local rate = 1
                    if count == 1 then -- Only apply the modifier for if there is one consumer type.
                        local k, v = next(t.components.finiteuses.consumption)
                        rate = v
                    end

                    AddInfo("finiteuses", (t.components.finiteuses.total / rate))
                end

                local _forgerepairmaterial = t.components.forgerepairable ~= nil and t.components.forgerepairable.repairmaterial or nil

                if _forgerepairmaterial ~= nil and REPAIR_MATERIAL_DATA[_forgerepairmaterial] ~= nil then
                    AddInfo("forgerepairable", REPAIR_MATERIAL_DATA[_forgerepairmaterial])
                end

                local _repairmaterial = t.components.repairable ~= nil and t.components.repairable.repairmaterial or nil
                if _repairmaterial and REPAIR_MATERIAL_DATA[_repairmaterial] ~= nil then
                    if not t.components.repairable.checkmaterialfn then
                        AddInfo("repairitems", REPAIR_MATERIAL_DATA[_repairmaterial])
                    else
                        local valid_materials = {}

                        for i, mat in ipairs(REPAIR_MATERIAL_DATA[_repairmaterial]) do
                            local mat_inst = SpawnPrefab(mat)

                            if mat_inst ~= nil and t.components.repairable.checkmaterialfn(t, mat_inst) then
                                table.insert(valid_materials, mat)
                            end

                            if mat_inst ~= nil then
                                mat_inst:Remove()
                            end
                        end

                        AddInfo("repairitems", valid_materials)
                    end
                end

                if t.components.tool ~= nil then
                    local actions = {}
                    for action, _ in pairs(t.components.tool.actions) do
                        table.insert(actions, action.id)
                    end
                    AddInfo("toolactions", actions)
                end

                ---------------------------------::   BUILD   ::---------------------------------

                AddInfo("scale", t.scrapbook_scale)
                AddInfo("animpercent", t.scrapbook_animpercent ~= nil and math.clamp(t.scrapbook_animpercent, 0, 1) or nil)
                AddInfo("overridebuild", t.scrapbook_overridebuild)
                AddInfo("hide", t.scrapbook_hide)
                AddInfo("hidesymbol", t.scrapbook_hidesymbol)

                AddInfo("build", t.scrapbook_build or t.AnimState:GetBuild())
                AddInfo("bank", t.scrapbook_bank or t.AnimState:GetCurrentBankName())
                AddInfo("anim", anim)

                AddInfo("alpha", t.scrapbook_alpha)

                if t.scrapbook_overridedata then
                    if type(t.scrapbook_overridedata[1]) ~= "table" then
                        AddInfo("overridesymbol", t.scrapbook_overridedata)
                    else
                        local overrides = {}

                        for _, tbl in ipairs(t.scrapbook_overridedata) do
                            table.insert(overrides, string.format('{"%s"}', table.concat(tbl, '", "')))
                        end

                        AddInfo("overridesymbol", string.format("{%s}", table.concat(overrides, ", ")))
                    end
                elseif t:HasTag("campfire") and entry ~= "cotl_tabernacle_level3" then
                    local blueflame = t:HasTag("blueflame")

                    local override = {
                        "flames_wide",                                -- Campfire Symbol.
                        blueflame and "coldfire_fire" or "campfire_fire", -- Fire Build.
                        blueflame and "coldflames_wide" or "flames_wide", -- Fire Symbol.
                    }

                    AddInfo("overridesymbol", override)
                end

                -- TODO(DiogoW): Refactor this.

                if t.prefab == "robin" then
                    AddInfo("animoffsety", -8)
                end
                if t.prefab == "robin_winter" then
                    AddInfo("animoffsety", -15)
                    AddInfo("animoffsetbgy", 15)
                end
                if t.prefab == "friendlyfruitfly" then
                    AddInfo("animoffsety", 65)
                end
                if t.prefab == "fruitfly" then
                    AddInfo("animoffsety", 65)
                end
                -------------------
                if t.prefab == "minotaur" then
                    AddInfo("animoffsetx", 5)
                end
                if t.prefab == "lordfruitfly" then
                    AddInfo("animoffsety", 70)
                end
                if t.prefab == "moonbutterfly" then
                    AddInfo("animoffsetx", 15)
                end
                if t.prefab == "bee" then
                    AddInfo("animoffsety", 150)
                end
                if t.prefab == "killerbee" then
                    AddInfo("animoffsety", 150)
                end
                if t.prefab == "lightflier" then
                    AddInfo("animoffsety", 70)
                end
                if t.prefab == "beeguard" then
                    AddInfo("animoffsety", 100)
                end
                if t.prefab == "mosquito" then
                    AddInfo("animoffsety", 100)
                    AddInfo("animoffsetx", -20)
                end
                if t.prefab == "moon_altar_seed" then
                    AddInfo("animoffsety", 20)
                    AddInfo("animoffsetx", 25)
                end
                if t.prefab == "moon_altar_glass" then
                    AddInfo("animoffsety", 20)
                    AddInfo("animoffsetx", 25)
                end
                if t.prefab == "moon_altar_icon" then
                    AddInfo("animoffsety", 25)
                    AddInfo("animoffsetx", 25)
                end
                if t.prefab == "moon_altar_ward" then
                    AddInfo("animoffsety", 20)
                    AddInfo("animoffsetx", 25)
                end
                if t.prefab == "moon_altar_crown" then
                    AddInfo("animoffsety", -20)
                    AddInfo("animoffsetx", 25)
                    AddInfo("animoffsetbgy", 30)
                end
                if t.prefab == "shroomcake" then
                    AddInfo("animoffsety", -20)
                    AddInfo("animoffsetbgy", 25)
                end
                if t.prefab == "vegstinger" then
                    AddInfo("animoffsety", -10)
                end
                if t.prefab == "watermelon_oversized" then
                    AddInfo("animoffsety", -20)
                    AddInfo("animoffsetbgy", 30)
                end
                if t.prefab == "saddle_war" then
                    AddInfo("animoffsety", -20)
                    AddInfo("animoffsetbgy", 30)
                end
                if t.prefab == "bunnyman" then
                    AddInfo("animoffsetx", 20)
                end
                if t.prefab == "bernie_active" then
                    AddInfo("animoffsety", 60)
                    AddInfo("animoffsetbgy", -50)
                end
                if t.prefab == "lightcrab" then
                    AddInfo("animoffsety", 60)
                    AddInfo("animoffsetbgy", -50)
                end
                if t.prefab == "fused_shadeling_bomb" then
                    AddInfo("animoffsety", 60)
                    AddInfo("animoffsetbgy", -50)
                end
                if t.prefab == "smallghost" then
                    AddInfo("animoffsety", 60)
                end
                if t.prefab == "wx78_scanner_item" then
                    AddInfo("animoffsety", 90)
                end
                if t.prefab == "eyeofterror_mini" then
                    AddInfo("animoffsety", 40)
                end
                if t.prefab == "dug_trap_starfish" then
                    AddInfo("animoffsetx", 160)
                    AddInfo("animoffsety", 10)
                end
                if t.prefab == "bananajuice" then
                    AddInfo("animoffsety", -20)
                end

                AddInfo("animoffsetx", t.scrapbook_animoffsetx)
                AddInfo("animoffsety", t.scrapbook_animoffsety)

                ---------------------------------::   WATERPROOFER   ::---------------------------------

                if t.components.waterproofer and t.components.waterproofer:GetEffectiveness() > 0 then
                    AddInfo("waterproofer", t.components.waterproofer:GetEffectiveness())
                end

                ---------------------------------::   INSULATOR   ::---------------------------------

                if t.components.insulator then
                    AddInfo("insulator", t.components.insulator:GetInsulation())
                    AddInfo("insulator_type", t.components.insulator.type)
                end

                ---------------------------------::   DAPPERNESS   ::---------------------------------

                if t.components.equippable and t.components.equippable.dapperness ~= 0 then
                    AddInfo("dapperness", t.components.equippable.dapperness)
                end

                ---------------------------------::   FUELED   ::---------------------------------

                if t.components.fueled then
                    AddInfo("fueledmax", t.scrapbook_fueled_max or t.components.fueled.maxfuel)
                    AddInfo("fueledrate", t.components.fueled.rate)
                    AddInfo("fueledtype1", t.components.fueled.fueltype)

                    if t.components.fueled.secondaryfueltype then
                        AddInfo("fueledtype2", t.components.fueled.secondaryfueltype)
                    end
                end

                local fueled = t.components.fueled
                if fueled ~= nil and (fueled.fueltype == FUELTYPE.USAGE or fueled.secondaryfueltype == FUELTYPE.USAGE) and not fueled.no_sewing then
                    AddInfo("sewable", true)
                end

                ---------------------------------::   FUEL   ::---------------------------------

                if t.components.fuel and t.components.inventoryitem then
                    AddInfo("fueltype", t.components.fuel.fueltype)
                    AddInfo("fuelvalue", t.components.fuel.fuelvalue)
                end

                if t:HasTag("lightbattery") then
                    AddInfo("lightbattery", true)
                end

                ---------------------------------::   PERISHABLE   ::---------------------------------

                if t.scrapbook_persishable then
                    AddInfo("perishable", t.scrapbook_persishable)
                elseif t.components.perishable then
                    AddInfo("perishable", t.components.perishable.perishtime)
                end

                ---------------------------------::   OAR   ::---------------------------------

                if t.components.oar then
                    AddInfo("oar_force", t.components.oar.force)
                    AddInfo("oar_velocity", t.components.oar.max_velocity)
                end

                ---------------------------------::   TACKLE   ::---------------------------------

                if t.components.oceanfishingtackle ~= nil then
                    if t.components.oceanfishingtackle.casting_data then
                        AddInfo("float_range", t.components.oceanfishingtackle.casting_data.dist_max + 5)
                        AddInfo("float_accuracy", t.components.oceanfishingtackle.casting_data.dist_min_accuracy)
                    end
                    if t.components.oceanfishingtackle.lure_data then
                        AddInfo("lure_charm", t.components.oceanfishingtackle.lure_data.charm)
                        AddInfo("lure_dist", t.components.oceanfishingtackle.lure_data.dist_max)
                        AddInfo("lure_radius", t.components.oceanfishingtackle.lure_data.radius)
                    end
                end

                ---------------------------------::   WORKABLE   ::---------------------------------

                if t.scrapbook_workable then
                    AddInfo("workable", t.scrapbook_workable)
                elseif t.components.workable and t.components.workable.action and t.components.workable.workleft > 0 then
                    AddInfo("workable", t.components.workable.action.id)
                end

                ---------------------------------::   PICKABLE   ::---------------------------------

                if t.components.pickable then
                    AddInfo("picakble", true)
                end

                ---------------------------------::   HARVESTABLE   ::---------------------------------

                if t.components.harvestable then
                    AddInfo("harvestable", true)
                end

                ---------------------------------::   STEWER   ::---------------------------------

                if t.components.stewer then
                    AddInfo("stewer", true)
                end

                ---------------------------------::   ACTIVATABLE   ::---------------------------------

                if t.components.activatable ~= nil and t.GetActivateVerb ~= nil then
                    AddInfo("activatable", t:GetActivateVerb(ThePlayer))
                end

                ---------------------------------::   FISHABLE   ::---------------------------------

                if t.components.fishable then
                    AddInfo("fishable", true)
                end

                ---------------------------------::   BURNABLE   ::---------------------------------

                if t.components.burnable ~= nil and
                    not t.components.burnable.ignorefuel and
                    t.components.burnable.canlight and
                    not table.contains({ "creature", "giant" }, thingtype)
                then
                    AddInfo("burnable", true)
                end

                ---------------------------------::   DEPENDENCIES   ::---------------------------------

                local _deps = t.scrapbook_deps or shallowcopy(Prefabs[entry].deps)

                local deps = {}

                for i, dep in ipairs(_deps) do
                    deps[dep] = true
                end

                if t.components.prototyper and t.prefab ~= "bookstation" then
                    for recipe, recipedata in pairs(AllRecipes) do
                        local found = false
                        for tech, level in pairs(recipedata.level) do
                            if level > 0 then
                                for tree, num in pairs(t.components.prototyper.trees) do
                                    if tech == tree and num >= level then
                                        deps[tostring(recipe)] = true
                                        found = true
                                        break
                                    end
                                end
                                if found then
                                    break
                                end
                            end
                        end
                    end
                end

                local recipe = AllRecipes[t.prefab]

                if recipe ~= nil then
                    if recipe.builder_tag then
                        ------  CRAFTING ICON  ------
                        local character = RECIPE_BUILDER_TAG_LOOKUP[recipe.builder_tag]

                        if character ~= nil then
                            AddInfo("craftingprefab", character)
                        else
                            print(string.format("[!!!!]  Recipe builder tag [%s] isn't in RECIPE_BUILDER_TAG_LOOKUP...", recipe.builder_tag))
                        end
                    end

                    for _, data in ipairs(recipe.ingredients) do
                        deps[data.type] = true
                    end
                end

                -- Loot.
                if t.components.lootdropper ~= nil then
                    for dep, _ in pairs(t.components.lootdropper:GetAllPossibleLoot(true)) do
                        deps[dep] = true
                    end
                end

                if t.components.vetcurselootdropper ~= nil and t.components.vetcurselootdropper.loot ~= nil then
                    deps[t.components.vetcurselootdropper.loot] = true
                end


                -- Deployable / Kits.
                local item_prefab = entry .. "_item"
                if scrapbookprefabs[item_prefab] then
                    deps[item_prefab] = true
                end

                local _perishable = t.components.perishable
                if _perishable ~= nil and _perishable.onperishreplacement ~= nil then
                    deps[_perishable.onperishreplacement] = true
                end

                -- Spawners.
                local _childspawner = t.components.childspawner
                if _childspawner ~= nil then
                    if _childspawner.childname ~= "" then
                        deps[_childspawner.childname] = true
                    end
                    if _childspawner.rarechild ~= nil then
                        deps[_childspawner.rarechild] = true
                    end
                end

                local _spawner = t.components.spawner
                if _spawner ~= nil and _spawner.childname ~= nil then
                    deps[_spawner.childname] = true
                end

                local _periodicspawner = t.components.periodicspawner
                if _periodicspawner ~= nil and _periodicspawner.prefab ~= nil then
                    deps[_periodicspawner.prefab] = true
                end

                local product_components = { "pickable", "cookable", "dryable", "harvestable" }

                for i, cmpname in ipairs(product_components) do
                    local _cmp = t.components[cmpname]
                    if _cmp ~= nil then
                        if _cmp.product ~= nil then
                            deps[_cmp.product] = true
                        end
                    end
                end

                if t:HasTag("waxable") then
                    deps.beeswax = true
                end

                -- Forge Repair Kits.
                if _forgerepairmaterial ~= nil and REPAIR_MATERIAL_DATA[_forgerepairmaterial] ~= nil then
                    for i, mat in ipairs(REPAIR_MATERIAL_DATA[_forgerepairmaterial]) do
                        deps[mat] = true
                    end
                end

                if t.scrapbook_adddeps then
                    for i, dep in ipairs(t.scrapbook_adddeps) do
                        if not table.contains(deps, dep) then
                            deps[dep] = true
                        else
                            print(string.format("[!!!!]  Dependency [%s] is duplicated in entry [%s]...", dep, entry))
                        end
                    end
                end

                if t.scrapbook_removedeps then
                    for i, dep in ipairs(t.scrapbook_removedeps) do
                        deps[dep] = nil
                    end
                end

                -- Remove itself if it exists.
                deps[entry] = nil

                for dep, _ in pairs(shallowcopy(deps)) do
                    if checkstring(dep) and dep:find("_blueprint") and not deps.blueprint then
                        deps.blueprint = true
                    end

                    if not scrapbookprefabs[dep] then
                        deps[dep] = nil
                    end
                end

                if next(deps) ~= nil then
                    deps = table.getkeys(deps)
                    table.sort(deps)
                    AddInfo("deps", deps)
                end

                ---------------------------------::   NOTES   ::---------------------------------

                local notes = {} -- Array of strings.

                if t:HasTag("shadow_aligned") then
                    table.insert(notes, "shadow_aligned=true")
                end

                if t:HasTag("lunar_aligned") then
                    table.insert(notes, "lunar_aligned=true")
                end

                if next(notes) ~= nil then
                    AddInfo("notes", string.format("{%s}", table.concat(notes, ", ")))
                end

                ---------------------------------::   SPECIAL INFO   ::---------------------------------

                if t.scrapbook_specialinfo ~= nil then
                    local info = string.upper(t.scrapbook_specialinfo)

                    if info ~= string.upper(t.scrapbook_prefab or entry) then
                        AddInfo("specialinfo", info)
                        specialinfo_list[info] = true
 
                        if not STRINGS.SCRAPBOOK.SPECIALINFO[info] then
                            print(string.format("[!!!!]  Special Information [ %s ] for entry [ %s ] isn't defined in STRINGS.SCRAPBOOK.SPECIALINFO!", info, entry))
                        end
                    elseif not SKIP_SPECIALINFO_CHECK[info] then
                        print(string.format("[!!!!]  Special Information [ %s ] for entry [ %s ] isn't required, as it's the name of the prefab!", info, entry))
                    end
                else
                    specialinfo_list[string.upper(t.scrapbook_prefab or entry)] = true
                end

                ---------------------------------::   END   ::---------------------------------

                t:Remove()
            end
        end
    end

    for info, _ in pairs(STRINGS.SCRAPBOOK.SPECIALINFO) do
        if specialinfo_list[info] == nil then
            print(string.format("[!!!!]  Special Information [ %s ] is in STRINGS.SCRAPBOOK.SPECIALINFO, but it's unused!", info))
        end
    end

    if print_missing_icons then
        print("\n\nScrapbook Missing Icons:\n")
        local str = {}
        for i, data in ipairs(icons_missing) do
            table.insert(str, (string.format("%s:\n    File: %s.fla\n    Animation: %s", data.icon, data.file, data.anim)))
        end

        print("\n" .. table.concat(str, "\n\n"))
    end

    Scrapbook_WriteToFile(scrapbookdata)

    exporter_data_helper:write("}\n")
    exporter_data_helper:close()

    print(prettyline)
end
