local prefabs = {
	--Characters
	"winky",
	"winky_none",
	--"wixie",
	--"wathom",
	--"winslow",
	--"wickett",
	--"winky2",
	--"whoppermeal",
	--"wackytobackey",
	--"wonaldmcronald

	"deathstick",
	"scrimbles_vanishing_sword",
	"uncompromising_toad",
	"mushroomsprout_overworld",
	"sporecloud_toad",
	"deerclops_ground_fx",
	"root_spike",
	"uncompromising_rat",
	"ratpoison",
	"ratpoison_debuff",
	--"ratpoisonbottle",
	"firemeteorwarning",
	"antlionwarning",
	"gasmask",
	"spiderqueencorpse",
	"lavae2",
	"mock_monsterwarningsounds",
	"mock_dragonfly",

	"moonmaw_dragonfly",
	"moonmaw_glass",
	"moonmaw_lavae",
	"glass_scales",
	"armor_glassmail",
	"armor_glassmail_shards",
	"moonmaw_trap",
	"moonmaw_glassshards",

	"lavaspit",
	--"um_sandhill",
	"snowpile",
	--"sand",
	"snowgoggles",
	"leechswarm", --buggy atm
	--"laitleech", Causes bug if not commmented out
	"shockworm",
	"zaspberry",
	"snowmong",
	"firedrop",
	"um_bearger_sinkhole",
	"minimoonspider_spike",
	"minotaur_boulder",
	"minotaur_boulder_big",
	--"monstermorsel",
	"bushcrab",
	"dreadeye",
	"creepingfear",
	"uncompromising_shadow_projectile_fx",
	"toadling",
	"iceboomerang",
	"diseasecure",
	"toadlingspawner",
	"extra_monsterfoods",
	"sporepack",
	"saltpack",
	"saltpile",
	"veteranshrine",
	"rat_tail",
	"shroom_skin_fragment",
	"plaguemask",
	"trapdoor",
	"spider_trapdoor",
	"antlion_sinkhole_lava",
	"lavaeslime",
	"air_conditioner",
	"air_conditioner_smoke",
	"mothergoose",
	"mothergooseegg",
	"shadow_goo",
	"mini_dreadeye",

	
	
	-- Broiling Fields
	"rock_lichen",
	"springrocks",
	"rocks_hotspring",
	"um_hotspring",
	"boulder_crab",	
	
	-- Lava Caves
	"lava_pond_cave",
	"magmabone",
	"magmarocks",
	
	
	"vampirebat",
	"icecreamsanityregenbuff",
	"zaspberryparfait",
	"uncompromising_foodbuffs",
	"shockfx",
	"shockstundebuff",
	"carapacecooler",
	"rnefissure",
	"honey_log",
	"pollenmites",
	"bugzapper",
	"moon_tear",
	"moon_tear_meteor",
	"rneghost",
	"chimp",
	"pollenmiteden",
	"pollenmitedenprefabspawner",
	"rice",
	--"gatorsnake",
	"riceplant",
	"acid_rain_splash",
	"walrus_camp_summer",
	"sunglasses",
	"cookiespikes",
	"skeletonmeat",
	"um_shadow_characters",
	"um_shadow_characters_temp",
	"veteranscurse",
	"healthregenbuff_vetcurse",
	"antlion_sinkhole_boat",
	"riceplantspawner",
	"critterlab_real",
	"charliephonograph",
	"stumpling",
	"shadow_teleporter",
	"shadow_teleporter_light",
	"shadowtalker",
	"shadow_crown",
	"trapdoorgrass",
	"trapdoorspawner",
	"lureplague_rat",
	"wicker_tentacle",
	"snapperturtle",
	"snapperturtlenest",
	"marsh_grass",
	"web_net_splat_fx",
	"web_bomb",
	"poopregenbuff",
	"giant_tree",
	"webbedcreature",
	"widowsgrasp",
	"extracanopyspawner",
	"widowweb",
	"widowwebspawner",
	"webbedcreaturespawner",
	"hoodedwidow",
	"willowfire",
	"berniebox",
	"chomper",
	"old_shadowwaxwell",
	"real_shadowwaxwell",
	"snapdragon",
	"snapdragonherd",
	"snapplant",
	"giant_blueberry",
	"blueberryplant",
	"blueberryplantbuncher",
	"rambranch",
	"rambranch_horn",
	"nightmarehorn",
	"sheeplet",
	"sheepletbomb",
	"whisperpod",
	"whisperpod_normal",
	"hooded_fern",
	"uncompromising_hounds",
	"hound_lightning",
	"aphid",
	"fruitbat",
	"pitcherplant",
	"widowshead",
	"cctrinkets",
	"pinepile",
	"hooded_mushtree",
	"hooded_forest_rubble",
	"rnelevitator",
	"screecher_trinket",
	"mushdrake_red",
	"rneshadowskittish",
	"cinnamon_tree",
	"watermelon_lantern",
	"gnome_organizer",
	"fireball_throwable",
	"ancient_trepidation",
	"ancient_trepidation_anchor",
	"ancient_amulet_red",
	"buff_ancient_amulet_red",
	"amulet_health_orb",
	"ancient_trepidation_arm",
	--"steel_sweater",
	"rat_whip",
	"bearger_mask",
	"rneskeleton",
	"snapdragon_fertilizer",
	"viperworm",
	"viperfruit",
	"viperjam",
	"viperprojectile",
	"bight",
	"knook",
	"roship",
	"deerclops_laser_blue",
	"gingerdeadpig_rne",
	"uncompromising_blowguns",
	"uncompromising_blowgun_ammo",
	"bearger_boulder",
	--"nymph",
	"deerclops_barrier",
	"roship_projectile",
	"electric_ring",

	"cave_entrance_sunkdecid",
	"cave_exit_sunkdecid",
	"cave_entrance_ratacombs",
	"cave_exit_ratacombs",

	"um_pawn",
	"pawn_spawn",
	"pigking_pigtorch",
	"armor_dragonfly_light",

	"mothermossling",
	"dragonfly_egg",
	"um_trap_snare",
	"um_bear_trap",
	"uncompromising_birds",
	"um_shambler",
	"um_shadowfire",
	"mothergoose_tornado",
	"corncan",
	"skullchest",
	"drink_with_the_living_dead",
	"hoodedturfchanger",
	"wargwarning",
	"deerclops_easyspawners",
	"armorlavae",
	"marshmist",
	"corvushat",
	"woomerang",
	"um_spider_mutators",
	--"uncompromising_alterguardianspawner",
	"driftwoodfishingrod",
	"nightlightfuel",

	
	"ratking",
	"ratgas",
	"ratacombs_junkpile",
	"ratacombs_junkpile_spawner",
	"ratacombslock",
	"ratacombskey",
	"ratacombslock_rock",
	"uncompromising_buffrat",
	"garbagespring",
	"uncompromising_bundles",
	"ratacombs_cleanair",
	"ratacombs_totem",
	--"ratgashole",

	"rneearthquake",
	"shadowvortex",
	"nervoustick",
	"mindweaver",
	"rneshadows",
	"fuelseeker",
	"um_heckler",
	"rnemushroombomb",
	"um_voxolophone",
	"um_haunt",
	"um_inkubator",
	"um_scrapper",
	"um_food_cubes",
	"um_nightcrawler",
	"um_shadow_leech",
	"um_shadowcloaked_smoke",
	"um_shadowcloaked_shield",
	"um_shadowcloaked_light",
	"um_shadow_miasma_cloud_fx",
	"um_shadow_characters",
	"um_shadow_abigail",
	

	"wackymask",
	"tiddlestranger_rne",
	"rne_goodiebag",


	--"moon_deerclops",
	"um_books",
	"rain_horn",
	"floral_bandage",
	"confighealbuff",
	"shockstundebuffimmunity",
	"pied_rat",
	"pied_piper_flute",

	"eyeofterror_laser",
	"eyeofterror_extras",
	"oculet",
	"oculet_pets",
	"terrarium",
	"reedbuncher",
	--"uncompromising_pollen_fx",
	"um_areahandler",
	"specter_shipwreck",
	--"proto_william",
	"phantom",
	--"spider_crabbit",
	--"resurrectionphonograph",
	"winona_toolbox",
	"searock_arches",
	"searock_ring",
	"minotaur_organ",
	"sunkenchest_royal",
	"speaker",
	"sludge",
	"sludgestack",
	"sludge_sack",
	"boatpatch_sludge",
	"beequeen_beering",
	--"siren_bubble",
	--"siren_debrisbarrier",
	"cave_entrance_lush",
	"uncompromising_rocks",
	--"uncompromising_superspawner",
	"uncompromising_devcapture",
	--"crab_apple_plant",
	"driftwood_waterlogged",
	"kelpstack",
	"siren_throne",
	--"spider_crabbit_den",
	--"um_siren_bird",
--DAMNIT SCRIMBLES
	"uncompromising_harpoon",
	"uncompromising_axepoon",
	"uncompromising_magharpoon",
	"uncompromising_fishingnet",
	"uncompromising_fishingnetvisualizer",
	"um_windturbine",
	"mastupgrade_windturbine",

	--"siren_fish",

	"armor_reed_um",
	"armor_sharksuit_um",
	"rockjawleather",
	"ocupus_beak",
	"ocupus_tentacles",
	"beakbasher",
	"winona_upgradekit",
	"powercell",
	"rr_powerline",
	"eyeofterror_mini_ally",
	"eyeofterror_mini_projectile_ally",

	"figgypet",
	"portableboat",
	"umbral_hound",
	"siren_bird_nest",
	"um_amber",
	"um_sorrel",
	"brine_balm",
	--"um_sandrock",
	"giant_tree_birdnest",
	"uncompromising_bumpers",
	"um_copper_pipe",
	"steeringwheel_copper",
	"hermit_bundle_lures",
	"um_cannonballs",
	"um_dreamcatcher",
	--"um_bombmixer_bombs",
	"um_beeguards",
	"um_beestinger_projectile",
	--"um_frog_ocean",
	--"um_tesla_tree",
	"um_specter_amulet",
	"um_walls",
	"um_ocupus_eyetacle",
	"ocupus_items",
	"houndious_observious",
	"ums_biometable",
	"umss_general",

	"um_tornado",
	"um_whirlpool",

	"um_waterfall",
	"um_waterfall_terraformer",

	"krampus_middleman_inventory",
	"alpha_lightninggoat",

	"wathom",
	"wathom_none",
	"wathom_heartbeat_ringfx",

	"um_shadowarena",

	"um_halloween_ornaments",
	"trinket_wathom1",

	"uncompromising_skins",

	"codex_mantra",
	"pact_armor_sanity",
	"pact_sword_sanity",

	--WIXIE RELATED PREFABS
	"charles_t_horse",
	"wixie_piano",
	"wixie_clock",
	"wixie_wardrobe",


	"uncompromising_skins",

	"codex_mantra",
	"um_ocupus",
	"um_ocupus_tentacle",
	"um_ocupus_beak",

	"slingshotammo_secondary",
	"slingshotammo_extras",
	"slingshotammo_IA",
	"slingshot_target",
	"wixie",
	"wixie_none",
	"wixiehoney_trail",
	"wixietar_trail",
	"wixie_stinkdebuff",
	"wixie_panicshield",
	"wixiecurse_debuff",
	"wixietaunt_debuff",
	"wixie_shockscrap_debuff",
	"wixie_stinger_debuff",
	"meatrack_hat",
	"walterbonus_buff",
	"bagofmarbles",
	"wixiebowling",
	"slingshot_gnasher",
	"slingshot_matilda",
	"slingshot_jessie",
	"slingshot_claire",
	"slingshot_planar_fx_lunar",
	"slingshot_planar_fx_shadow",
	"shadow_wixie",
	"dried_fishmeats",
	"bigwoby_debuff",
	"woby_target",
	"wixie_stinkcloud",
	"wixie_reticuleline",
	"wixiegun",
	
	"winona_structure_item",
	"boiling_water",
	"crabking_geyser_single",
	"staff_starfall",
	"staff_moonfall",
	"armor_crab",
	"hat_crab",
	"trident_ground_fx",
	"moon_beacon",

	--"um_bombmixer1",
	"moon_beacon",
	--"um_bombmixer_bombs2",
	--"um_bombmixer",
	"goat_lightning",

	--	"um_bombmixer1",
	--	"um_bombmixer",
	--	"um_bombmixer_bombs2",

	"mara_boss1",
	"mara_boss1_bullets",
	"um_WITCH",
	"um_sacred_chest",
	"smog",
    
	-- Pyre Nettle stuff
	"um_pyre_nettles",
	"um_smolder_spore",
	"umdebuff_pyre_toxin",
	"um_armor_pyre_nettles",
	"um_blowdart_pyre",
	
	-- Rimeweed Stuff
	"rimeweed",
	
	-- Mutation Extrapolation
	"umdebuff_moonburn",
	"um_pathfinderpulse",
	
	"um_preparedfoods",
	"um_foliage",
	"lifeinjector_redcap_buff",
	
	--The Cursed!
	"cursed_antler",
	"feather_frock",
	"slobberlobber",
	"beargerclaw",
	"klaus_amulet",
	"gore_horn_hat",
	"crabclaw",
	"um_beegun",
	
	"silksack",
	"um_moonfly_lantern",
	"um_exhumer",
	"um_wingsuit",
	
	--"um_twin_masks",
	--"um_moon_flask",
	--"um_web_staff",
	--"um_wishbone",
	--"um_sand_staff",
	
	"um_records",

    "dl_prefabs",
    "dl_biometable",

    "sea_shadow",
    "kaleidoscope",
    "moonglow",
    --"um_boat_engine",

    "garbagepatchflotsam",
    "garbagepatch_inventory",
	
	"um_astral_projector",
	
	-- Broiling Hills & Magma Caves
	"snaildrake_explosion",
    "snaildrake_hole",
    "snaildrake_projectiles",
    "snaildrake_slime_debuff",
    "snaildrake",
    "snapalm",
	"snaildrakehat",
	"snaildrakebucket",
	"cave_entrance_magmabiome",
	"cave_exit_magmabiome",
	"mushtree_shadow",
	"viperfruit_plant",
	"zaspberry_plant",
	"um_blowdart_rime",
	"um_armor_bramble_rimeweed",


	"um_robust_projectile",
	--"coffbee",
	"um_cookpot_wagstaff",
	"um_ghost_peppers",

    "um_boatbottle",
	"jawed_scythe",
	"um_fire_projectile",
	"um_buttery_fly",
	
	"um_thicket_builders",
	"um_hat_leafwing",
	"um_meats",
	
	"um_detonator",
	"um_fyrite",
	
	"um_bee_moon",
	"um_fyre_bomb",
	"um_beehive_moon",
	"um_manny",
	"um_steamcloud",
}

if TUNING.DSTU ~= nil and TUNING.DSTU.WIXIE ~= nil and TUNING.DSTU.WIXIE then
	table.insert(prefabs, "placeholder_recipe_item")
end

return prefabs